#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Wakemaker

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "ABP_Wakemaker_structs.hpp"
#include "ControlRig_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Wakemaker.ABP_Wakemaker_C
// 0x06C0 (0x0AA0 - 0x03E0)
class UABP_Wakemaker_C final : public UAnimInstance
{
public:
	uint8                                         Pad_3D8[0x8];                                      // 0x03D8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct ABP_Wakemaker::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                // 0x03E8(0x0002)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3EA[0x6];                                      // 0x03EA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x03F0(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x03F8(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0400(0x0020)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x0420(0x0158)(ContainsInstancedReference)
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x0578(0x0050)()
	struct FAnimNode_RefPose                      AnimGraphNode_LocalRefPose;                        // 0x05C8(0x0010)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig;                          // 0x05D8(0x04B8)(ContainsInstancedReference)
	class USkeletalMeshComponent*                 Source_Mesh_Component;                             // 0x0A90(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          ValidSourceMesh;                                   // 0x0A98(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void ExecuteUbergraph_ABP_Wakemaker(int32 EntryPoint);
	void SetCarryActor(class AActor* Actor);
	void SetMeshDriver(class USkeletalMeshComponent* SourceMeshComponent);
	void SetSourceMeshComponent();
	void SetToolEnergy(double EnergyLevel);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Wakemaker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Wakemaker_C")
	}
	static class UABP_Wakemaker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Wakemaker_C>();
	}
};
DUMPER7_ASSERTS_UABP_Wakemaker_C;

}

