#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_SN2PlayerCharacter

#include "Basic.hpp"

#include "ALI_SN2PlayerCharacter_classes.hpp"
#include "ALI_SN2PlayerCharacter_parameters.hpp"


namespace SDK
{

// Function ALI_SN2PlayerCharacter.ALI_SN2PlayerCharacter_C.Carryable Locker
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 Input_Pose                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       Carryable_Locker_0                                     (Parm, OutParm, NoDestructor)

void IALI_SN2PlayerCharacter_C::Carryable_Locker(const struct FPoseLink& Input_Pose, struct FPoseLink* Carryable_Locker_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_SN2PlayerCharacter_C", "Carryable Locker");

	Params::ALI_SN2PlayerCharacter_C_Carryable_Locker Parms{};

	Parms.Input_Pose = std::move(Input_Pose);

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Carryable_Locker_0 != nullptr)
		*Carryable_Locker_0 = std::move(Parms.Carryable_Locker_0);
}


// Function ALI_SN2PlayerCharacter.ALI_SN2PlayerCharacter_C.Carryable None
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       Carryable_None_0                                       (Parm, OutParm, NoDestructor)

void IALI_SN2PlayerCharacter_C::Carryable_None(struct FPoseLink* Carryable_None_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_SN2PlayerCharacter_C", "Carryable None");

	Params::ALI_SN2PlayerCharacter_C_Carryable_None Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Carryable_None_0 != nullptr)
		*Carryable_None_0 = std::move(Parms.Carryable_None_0);
}


// Function ALI_SN2PlayerCharacter.ALI_SN2PlayerCharacter_C.Vehicle Attach
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       Vehicle_Attach_0                                       (Parm, OutParm, NoDestructor)

void IALI_SN2PlayerCharacter_C::Vehicle_Attach(const struct FPoseLink& InPose, struct FPoseLink* Vehicle_Attach_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("ALI_SN2PlayerCharacter_C", "Vehicle Attach");

	Params::ALI_SN2PlayerCharacter_C_Vehicle_Attach Parms{};

	Parms.InPose = std::move(InPose);

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Vehicle_Attach_0 != nullptr)
		*Vehicle_Attach_0 = std::move(Parms.Vehicle_Attach_0);
}

}

