#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AxumDataCache

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_BasicItemBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AxumDataCache.BP_AxumDataCache_C
// 0x0038 (0x03F0 - 0x03B8)
class ABP_AxumDataCache_C final : public ABP_BasicItemBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPointLightComponent*                   PointLight;                                        // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Cube1;                                             // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Cube;                                              // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWEAssetDataComponent*                 UWEAssetData;                                      // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_LightPulse_5911D98643E773D166C61985FBCCCFE6; // 0x03E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline__Direction_5911D98643E773D166C61985FBCCCFE6; // 0x03E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3E5[0x3];                                      // 0x03E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline;                                          // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_AxumDataCache(int32 EntryPoint);
	void ReceiveBeginPlay();
	void Timeline__FinishedFunc();
	void Timeline__UpdateFunc();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AxumDataCache_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AxumDataCache_C")
	}
	static class ABP_AxumDataCache_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AxumDataCache_C>();
	}
};
DUMPER7_ASSERTS_ABP_AxumDataCache_C;

}

