#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BasicBatteryTerminal

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "UWESculpturalBase_structs.hpp"
#include "UWEInterfaces_structs.hpp"
#include "Engine_structs.hpp"
#include "UWEPower_structs.hpp"


namespace SDK::Params
{

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.AddSlot
// 0x0018 (0x0018 - 0x0000)
struct BP_BasicBatteryTerminal_C_AddSlot final
{
public:
	class UChildActorComponent*                   SlotChildActorComponent;                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ABP_PowerTerminalSlot_C*                K2Node_DynamicCast_AsBP_Power_Terminal_Slot;       // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_AddSlot;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.BndEvt__BP_PowerTerminalBasic_UWEAttachable_K2Node_ComponentBoundEvent_0_OnAttached__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BP_BasicBatteryTerminal_C_BndEvt__BP_PowerTerminalBasic_UWEAttachable_K2Node_ComponentBoundEvent_0_OnAttached__DelegateSignature final
{
public:
	class AActor*                                 AttachedTo;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_BndEvt__BP_PowerTerminalBasic_UWEAttachable_K2Node_ComponentBoundEvent_0_OnAttached__DelegateSignature;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.CanBeDeconstructed
// 0x000C (0x000C - 0x0000)
struct BP_BasicBatteryTerminal_C_CanBeDeconstructed final
{
public:
	struct FGameplayTag                           CantDeconstructReason;                             // 0x0000(0x0008)(Parm, OutParm, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_CanBeDeconstructed;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.ExecuteUbergraph_BP_BasicBatteryTerminal
// 0x0410 (0x0410 - 0x0000)
struct BP_BasicBatteryTerminal_C_ExecuteUbergraph_BP_BasicBatteryTerminal final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUWETerminalBatteryData                CallFunc_GetBatteryData_Data;                      // 0x0010(0x0028)(NoDestructor)
	bool                                          CallFunc_GetBatteryData_ReturnValue;               // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASN2BuilderTool*                        K2Node_Event_BuilderTool;                          // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AController*                            K2Node_Event_Controller_5;                         // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_Pawn_5;                               // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_HitResult_2;                          // 0x0060(0x0100)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AController*                            K2Node_Event_Controller_4;                         // 0x0160(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_Pawn_4;                               // 0x0168(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_HitResult_1;                          // 0x0170(0x0100)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AController*                            K2Node_Event_Controller_3;                         // 0x0270(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_Pawn_3;                               // 0x0278(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AController*                            K2Node_Event_Controller_2;                         // 0x0280(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_Pawn_2;                               // 0x0288(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AController*                            K2Node_Event_Controller_1;                         // 0x0290(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_Pawn_1;                               // 0x0298(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x02A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A4[0x4];                                      // 0x02A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_ComponentBoundEvent_AttachedTo;             // 0x02A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_PowerTerminalSlot_C*                CallFunc_Array_Get_Item;                           // 0x02B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x02B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2BC[0x4];                                      // 0x02BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            K2Node_Event_Controller;                           // 0x02C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_Pawn;                                 // 0x02C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_HitResult;                            // 0x02D0(0x0100)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x03D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D1[0x3];                                      // 0x03D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool ChargingEnabled)>         K2Node_CreateDelegate_OutputDelegate;              // 0x03D4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_ChargingEnabled;                // 0x03E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3E5[0x3];                                      // 0x03E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_GetWidget_ReturnValue;                    // 0x03E8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_PowerTerminalReserveScreen_C*      K2Node_DynamicCast_AsWBP_Power_Terminal_Reserve_Screen; // 0x03F0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x03F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3F9[0x7];                                      // 0x03F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Divide_DoubleDouble_A_ImplicitCast;       // 0x0400(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_B_ImplicitCast;       // 0x0408(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_ExecuteUbergraph_BP_BasicBatteryTerminal;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.GetDeconstructCostOverride
// 0x0018 (0x0018 - 0x0000)
struct BP_BasicBatteryTerminal_C_GetDeconstructCostOverride final
{
public:
	TArray<struct FUWESculpturalBaseCellCost>     Costs;                                             // 0x0000(0x0010)(Parm, OutParm)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_GetDeconstructCostOverride;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.GetInteractionInfo
// 0x01C8 (0x01C8 - 0x0000)
struct BP_BasicBatteryTerminal_C_GetInteractionInfo final
{
public:
	class AActor*                                 HoverActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 ForActor;                                          // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    HoverComponent;                                    // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             HitResult;                                         // 0x0018(0x0100)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FInteractionInfo                       ReturnValue;                                       // 0x0118(0x0038)(Parm, OutParm, ReturnParm)
	struct FInteractionInfo                       K2Node_MakeStruct_InteractionInfo;                 // 0x0150(0x0038)()
	struct FInteractionInfo                       K2Node_MakeStruct_InteractionInfo_1;               // 0x0188(0x0038)()
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_GetInteractionInfo;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.InitializeSlots
// 0x0038 (0x0038 - 0x0000)
struct BP_BasicBatteryTerminal_C_InitializeSlots final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UChildActorComponent*>           K2Node_MakeArray_Array;                            // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UChildActorComponent*                   CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_InitializeSlots;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.Interact
// 0x0110 (0x0110 - 0x0000)
struct BP_BasicBatteryTerminal_C_Interact final
{
public:
	class AController*                            Controller;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  Pawn;                                              // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             HitResult;                                         // 0x0010(0x0100)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_Interact;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.InteractClient
// 0x0110 (0x0110 - 0x0000)
struct BP_BasicBatteryTerminal_C_InteractClient final
{
public:
	class AController*                            Controller;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  Pawn;                                              // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             HitResult;                                         // 0x0010(0x0100)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_InteractClient;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.InteractEnd
// 0x0010 (0x0010 - 0x0000)
struct BP_BasicBatteryTerminal_C_InteractEnd final
{
public:
	class AController*                            Controller;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  Pawn;                                              // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_InteractEnd;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.InteractEndClient
// 0x0010 (0x0010 - 0x0000)
struct BP_BasicBatteryTerminal_C_InteractEndClient final
{
public:
	class AController*                            Controller;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  Pawn;                                              // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_InteractEndClient;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.InteractEndServer
// 0x0010 (0x0010 - 0x0000)
struct BP_BasicBatteryTerminal_C_InteractEndServer final
{
public:
	class AController*                            Controller;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  Pawn;                                              // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_InteractEndServer;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.InteractionDistance
// 0x0004 (0x0004 - 0x0000)
struct BP_BasicBatteryTerminal_C_InteractionDistance final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_InteractionDistance;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.InteractServer
// 0x0110 (0x0110 - 0x0000)
struct BP_BasicBatteryTerminal_C_InteractServer final
{
public:
	class AController*                            Controller;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  Pawn;                                              // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             HitResult;                                         // 0x0010(0x0100)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_InteractServer;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.IsInteractDisabled
// 0x0128 (0x0128 - 0x0000)
struct BP_BasicBatteryTerminal_C_IsInteractDisabled final
{
public:
	class AActor*                                 HoverActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 ForActor;                                          // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         Distance;                                          // 0x0010(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    HoverComponent;                                    // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             HitResult;                                         // 0x0020(0x0100)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x0120(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_IsInteractDisabled;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.OnUseReservePowerChanged_Event
// 0x0001 (0x0001 - 0x0000)
struct BP_BasicBatteryTerminal_C_OnUseReservePowerChanged_Event final
{
public:
	bool                                          ChargingEnabled_0;                                 // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_OnUseReservePowerChanged_Event;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.PreDeconstruct
// 0x0008 (0x0008 - 0x0000)
struct BP_BasicBatteryTerminal_C_PreDeconstruct final
{
public:
	class ASN2BuilderTool*                        BuilderTool;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_PreDeconstruct;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_BasicBatteryTerminal_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_ReceiveTick;

// Function BP_BasicBatteryTerminal.BP_BasicBatteryTerminal_C.ShouldDeconstructInstantly
// 0x0001 (0x0001 - 0x0000)
struct BP_BasicBatteryTerminal_C_ShouldDeconstructInstantly final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BasicBatteryTerminal_C_ShouldDeconstructInstantly;

}

