#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Bioreactor_Scannable

#include "Basic.hpp"

#include "BP_Scannable_BaseClass_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Bioreactor_Scannable.BP_Bioreactor_Scannable_C
// 0x0000 (0x02E0 - 0x02E0)
class ABP_Bioreactor_Scannable_C final : public ABP_Scannable_BaseClass_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Bioreactor_Scannable_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Bioreactor_Scannable_C")
	}
	static class ABP_Bioreactor_Scannable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Bioreactor_Scannable_C>();
	}
};
DUMPER7_ASSERTS_ABP_Bioreactor_Scannable_C;

}

