#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Blackbox_Clickable_01a

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Blackbox_Clickable_01a.BP_Blackbox_Clickable_01a_C
// 0x0048 (0x02F8 - 0x02B0)
class ABP_Blackbox_Clickable_01a_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Niagara;                                           // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BlackboxMesh;                                      // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BaseMesh;                                          // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_ProximityTextComponent_C*          BPC_ProximityTextComponent;                        // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWEFMODAudioComponent*                 FMODAudio;                                         // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWEStoryGoal*                          StoryGoal;                                         // 0x02E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          DisableSFX;                                        // 0x02F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Blackbox_Clickable_01a(int32 EntryPoint);
	struct FInteractionInfo GetInteractionInfo(class AActor* HoverActor, class AActor* ForActor, class UPrimitiveComponent* HoverComponent, const struct FHitResult& HitResult);
	void Interact(class AController* Controller, class APawn* Pawn, const struct FHitResult& HitResult);
	void InteractClient(class AController* Controller, class APawn* Pawn, const struct FHitResult& HitResult);
	void InteractEnd(class AController* Controller, class APawn* Pawn);
	void InteractEndClient(class AController* Controller, class APawn* Pawn);
	void InteractEndServer(class AController* Controller, class APawn* Pawn);
	float InteractionDistance();
	void InteractServer(class AController* Controller, class APawn* Pawn, const struct FHitResult& HitResult);
	bool IsInteractDisabled(class AActor* HoverActor, class AActor* ForActor, float Distance, class UPrimitiveComponent* HoverComponent, const struct FHitResult& HitResult);
	void OnUnlocked_07BDEFDA4F7F51B7910FA1BD9757E4B0();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Blackbox_Clickable_01a_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Blackbox_Clickable_01a_C")
	}
	static class ABP_Blackbox_Clickable_01a_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Blackbox_Clickable_01a_C>();
	}
};
DUMPER7_ASSERTS_ABP_Blackbox_Clickable_01a_C;

}

