#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BaseModule_RoomWall_Hatch_01b

#include "Basic.hpp"

#include "BP_Bases_KitPieces_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BaseModule_RoomWall_Hatch_01b.BP_BaseModule_RoomWall_Hatch_01b_C
// 0x0078 (0x0348 - 0x02D0)
class BP_BaseModule_RoomWall_Hatch_01b::ABP_BaseModule_RoomWall_Hatch_01b_C final : public ABP_Bases_KitPieces_Parent_C
{
public:
	class UStaticMeshComponent*                   SM_Room_Interior_FlatWall_Top_A20;                 // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_Interior_FlatWall_Top_A21;                 // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_Interior_FlatWall_Top_A22;                 // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_Interior_FlatWall_Top_A8;                  // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_Interior_FlatWall_Top_A9;                  // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_Interior_FlatWall_Top_A10;                 // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_Interior_FlatWall_Top_A12;                 // 0x0300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_Interior_FlatWall_Top_A13;                 // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_Interior_FlatWall_Top_A14;                 // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_FlatWall_Exterior_A704_StaticMeshComponent0; // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_Interior_FlatWall_Top_A31;                 // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_Interior_FlatWall_Top_A29;                 // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_Interior_FlatWall_Top_A30;                 // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Scene;                                             // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        SharedRoot;                                        // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_BaseModule_RoomWall_Hatch_01b.BP_BaseModule_RoomWall_Hatch_01b_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BaseModule_RoomWall_Hatch_01b_C")
	}
	static class BP_BaseModule_RoomWall_Hatch_01b::ABP_BaseModule_RoomWall_Hatch_01b_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_BaseModule_RoomWall_Hatch_01b::ABP_BaseModule_RoomWall_Hatch_01b_C>();
	}
};
DUMPER7_ASSERTS_BP_BaseModule_RoomWall_Hatch_01b__ABP_BaseModule_RoomWall_Hatch_01b_C;

}

