#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BaseModule_DisplayCase_01b

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_BaseModule_DisplayCase_01b.BP_BaseModule_DisplayCase_01b_C.ExecuteUbergraph_BP_BaseModule_DisplayCase_01b
// 0x0004 (0x0004 - 0x0000)
struct BP_BaseModule_DisplayCase_01b_C_ExecuteUbergraph_BP_BaseModule_DisplayCase_01b final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BaseModule_DisplayCase_01b_C_ExecuteUbergraph_BP_BaseModule_DisplayCase_01b;

// Function BP_BaseModule_DisplayCase_01b.BP_BaseModule_DisplayCase_01b_C.UserConstructionScript
// 0x0002 (0x0002 - 0x0000)
struct BP_BaseModule_DisplayCase_01b_C_UserConstructionScript final
{
public:
	bool                                          CallFunc_SetStaticMesh_ReturnValue;                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetStaticMesh_ReturnValue_1;              // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BaseModule_DisplayCase_01b_C_UserConstructionScript;

}

