#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ClientLobbyGameMode

#include "Basic.hpp"

#include "BP_ClientLobbyGameMode_classes.hpp"
#include "BP_ClientLobbyGameMode_parameters.hpp"


namespace SDK
{

// Function BP_ClientLobbyGameMode.BP_ClientLobbyGameMode_C.ExecuteUbergraph_BP_ClientLobbyGameMode
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ClientLobbyGameMode_C::ExecuteUbergraph_BP_ClientLobbyGameMode(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClientLobbyGameMode_C", "ExecuteUbergraph_BP_ClientLobbyGameMode");

	Params::BP_ClientLobbyGameMode_C_ExecuteUbergraph_BP_ClientLobbyGameMode Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ClientLobbyGameMode.BP_ClientLobbyGameMode_C.HostSession
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    GameModeAlias                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    ServerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    SaveSlot                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    SaveCheckpoint                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_ClientLobbyGameMode_C::HostSession(const class FString& GameModeAlias, const class FString& ServerName, const class FString& SaveSlot, const class FString& SaveCheckpoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClientLobbyGameMode_C", "HostSession");

	Params::BP_ClientLobbyGameMode_C_HostSession Parms{};

	Parms.GameModeAlias = std::move(GameModeAlias);
	Parms.ServerName = std::move(ServerName);
	Parms.SaveSlot = std::move(SaveSlot);
	Parms.SaveCheckpoint = std::move(SaveCheckpoint);

	UObject::ProcessEvent(Func, &Parms);
}

}

