#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_JetoCaris

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_SN2AILargeFish_classes.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_JetoCaris.BP_JetoCaris_C
// 0x0038 (0x0508 - 0x04D0)
class ABP_JetoCaris_C final : public ABP_SN2AILargeFish_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBPC_CreatureAnimationComponent_C*      BPC_CreatureAnimationComponent;                    // 0x04D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWEStimulusSystemComponent*            UWEStimulusSystem;                                 // 0x04E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWEPawnAttachmentOwner*                UWEPawnAttachmentOwner;                            // 0x04E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWEAssetDataComponent*                 UWEAssetData;                                      // 0x04F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         JuvenilesAmountMaximum;                            // 0x04F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         JuvenilesAmount;                                   // 0x04FC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           HabitationAreaTag_InsideCave;                      // 0x0500(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_JetoCaris(int32 EntryPoint);
	void GetWorldLocation(struct FVector* Location);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_JetoCaris_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_JetoCaris_C")
	}
	static class ABP_JetoCaris_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_JetoCaris_C>();
	}
};
DUMPER7_ASSERTS_ABP_JetoCaris_C;

}

