#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lighting_Alterra_02

#include "Basic.hpp"

#include "BP_Lighting_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Lighting_Alterra_02.BP_Lighting_Alterra_02_C
// 0x0000 (0x0380 - 0x0380)
class ABP_Lighting_Alterra_02_C final : public ABP_Lighting_Master_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Lighting_Alterra_02_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Lighting_Alterra_02_C")
	}
	static class ABP_Lighting_Alterra_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Lighting_Alterra_02_C>();
	}
};
DUMPER7_ASSERTS_ABP_Lighting_Alterra_02_C;

}

