#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MarrowbreachRoarCameraShake

#include "Basic.hpp"

#include "EngineCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MarrowbreachRoarCameraShake.BP_MarrowbreachRoarCameraShake_C
// 0x0000 (0x00E0 - 0x00E0)
class UBP_MarrowbreachRoarCameraShake_C final : public UDefaultCameraShakeBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MarrowbreachRoarCameraShake_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MarrowbreachRoarCameraShake_C")
	}
	static class UBP_MarrowbreachRoarCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MarrowbreachRoarCameraShake_C>();
	}
};
DUMPER7_ASSERTS_UBP_MarrowbreachRoarCameraShake_C;

}

