#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Marrowbreach

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "BP_SN2AILargeFish_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Marrowbreach.BP_Marrowbreach_C
// 0x0088 (0x0558 - 0x04D0)
class ABP_Marrowbreach_C : public ABP_SN2AILargeFish_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBPC_SN2PhysicalAnimation_C*            BPC_SN2PhysicalAnimation;                          // 0x04D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPhysicalAnimationComponent*            PhysicalAnimation;                                 // 0x04E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_InfectedSkeletalMesh_C*            Infection_03;                                      // 0x04E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_InfectedSkeletalMesh_C*            Infection_01;                                      // 0x04F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_InfectedSkeletalMesh_C*            Infection_02;                                      // 0x04F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_CreatureAnimationComponent_C*      BPC_CreatureAnimationComponent;                    // 0x0500(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWEStimulusSystemComponent*            UWEStimulusSystem;                                 // 0x0508(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWEAssetDataComponent*                 UWEAssetData;                                      // 0x0510(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWEPawnAttachmentOwner*                UWEPawnAttachmentOwner;                            // 0x0518(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               Body_Material;                                     // 0x0520(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UABP_MarrowBreach_01_C*                 ABP_MarrowBreach;                                  // 0x0528(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           TargetColour;                                      // 0x0530(0x0010)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TargetFinsEmissiveStrength;                        // 0x0540(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        FinsEmissiveStrength;                              // 0x0548(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        EmissiveTransitionDuration;                        // 0x0550(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void DISINFECT_1();
	void DISINFECT_ALL();
	void ExecuteUbergraph_BP_Marrowbreach(int32 EntryPoint);
	void INFECT_1();
	void INFECT_ALL();
	void ReceiveBeginPlay();
	void Set_Fins_Emissive(const struct FLinearColor& Colour, double Strength, double Transition);
	void ShowPosture(double PostureNormal, double LerpDuration);
	void ShowThreat(const struct FLinearColor& EmissiveColour, double EmissiveNormal, double LerpDuration);
	void TickFinsEmissive(class UMaterialInstance* Material, const struct FLinearColor& Color, double Target_Value, double Delta_Seconds, double duration);
	void TickFinsPhysics(class UABP_MarrowBreach_01_C* AnimInstance, double Target_Value, double Delta_Seconds, double duration);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Marrowbreach_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Marrowbreach_C")
	}
	static class ABP_Marrowbreach_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Marrowbreach_C>();
	}
};
DUMPER7_ASSERTS_ABP_Marrowbreach_C;

}

