#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NarrativeSignal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NarrativeSignal.BP_NarrativeSignal_C
// 0x0058 (0x0308 - 0x02B0)
class ABP_NarrativeSignal_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUWESaveComponent*                      UWESave;                                           // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FGuid                                  Ping;                                              // 0x02C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUWEStoryGoal*                          StoryGoal;                                         // 0x02D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   SignalText;                                        // 0x02E0(0x0010)(Edit, BlueprintVisible)
	class UUWEPingData*                           Ping_Data;                                         // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUWEStoryGoal*                          RemoveOnStoryGoal;                                 // 0x02F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UUWEStoryGoal*                          HideSignalOnStoryGoal;                             // 0x0300(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_NarrativeSignal(int32 EntryPoint);
	void OnUnlocked_62920D1448BD71509596E5B554437304();
	void OnUnlocked_798D037D414E64E523303188A5B43EF4();
	void OnUnlocked_DD1B37CE44DE0D7179F153871FC8B746();
	void ReceiveBeginPlay();
	void RemovePing();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NarrativeSignal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NarrativeSignal_C")
	}
	static class ABP_NarrativeSignal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NarrativeSignal_C>();
	}
};
DUMPER7_ASSERTS_ABP_NarrativeSignal_C;

}

