#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NeedlerSharkStarveCalc

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NeedlerSharkStarveCalc.BP_NeedlerSharkStarveCalc_C
// 0x0000 (0x0040 - 0x0040)
class UBP_NeedlerSharkStarveCalc_C final : public UGameplayModMagnitudeCalculation
{
public:
	float CalculateBaseMagnitude(const struct FGameplayEffectSpec& Spec) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NeedlerSharkStarveCalc_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NeedlerSharkStarveCalc_C")
	}
	static class UBP_NeedlerSharkStarveCalc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NeedlerSharkStarveCalc_C>();
	}
};
DUMPER7_ASSERTS_UBP_NeedlerSharkStarveCalc_C;

}

