#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OR_AB01_Room_03

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_OR_AB01_Room_03.BP_OR_AB01_Room_03_C
// 0x0078 (0x0328 - 0x02B0)
class ABP_OR_AB01_Room_03_C final : public AActor
{
public:
	class UInstancedStaticMeshComponent*          Actor1_InstancedStaticMeshComponent_5;             // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UInstancedStaticMeshComponent*          Actor1_InstancedStaticMeshComponent_6;             // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UInstancedStaticMeshComponent*          Actor1_InstancedStaticMeshComponent_7;             // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UInstancedStaticMeshComponent*          Actor1_InstancedStaticMeshComponent_8;             // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UInstancedStaticMeshComponent*          Actor1_InstancedStaticMeshComponent_3;             // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UInstancedStaticMeshComponent*          Actor1_InstancedStaticMeshComponent_10;            // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UInstancedStaticMeshComponent*          Actor1_InstancedStaticMeshComponent_4;             // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UInstancedStaticMeshComponent*          Actor1_InstancedStaticMeshComponent_1;             // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UInstancedStaticMeshComponent*          Actor1_InstancedStaticMeshComponent_2;             // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UInstancedStaticMeshComponent*          Actor1_InstancedStaticMeshComponent_9;             // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UInstancedStaticMeshComponent*          Actor1_InstancedStaticMeshComponent_0;             // 0x0300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Room_Greebles_Exterior_OutsideCorner_Top_Vent3_StaticMeshComponent0; // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Hatch_Corridor_Room_Junction6_StaticMeshComponent0; // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_EmbeddedActors_HalfRoundRoom_Exterior_B5_StaticMeshComponent0; // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        SharedRoot;                                        // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_OR_AB01_Room_03_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_OR_AB01_Room_03_C")
	}
	static class ABP_OR_AB01_Room_03_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_OR_AB01_Room_03_C>();
	}
};
DUMPER7_ASSERTS_ABP_OR_AB01_Room_03_C;

}

