#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RecipeGainDataCard_Button

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "UWEGameModeTypes_structs.hpp"
#include "FMODStudio_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RecipeGainDataCard_Button.BP_RecipeGainDataCard_Button_C
// 0x00D0 (0x0380 - 0x02B0)
class ABP_RecipeGainDataCard_Button_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUWEFMODAudioComponent*                 sfx_databox_unopened_loop;                         // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NS_DataCard_HologramProjector;                     // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxCollision;                                      // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Databox_Chip;                                   // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Databox_Panel_B;                                // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Databox_Panel_A;                                // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Databox_Lid;                                    // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Databox_Interior;                               // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Databox_ChipHinge;                              // 0x0300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Components;                                        // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Scene;                                             // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWESaveComponent*                      UWESave;                                           // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWEUnlockStoryGoalAction*              UWEUnlockStoryGoalAction;                          // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_Opacity_18C672A5497F426DB21F87A9E8ECE520; // 0x0328(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_Animate_18C672A5497F426DB21F87A9E8ECE520; // 0x032C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline__Direction_18C672A5497F426DB21F87A9E8ECE520; // 0x0330(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_331[0x7];                                      // 0x0331(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline;                                          // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<int32>                                 IntereactedPlayerStateIDs;                         // 0x0340(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnInstance, SaveGame)
	TArray<TSoftObjectPtr<class UUWEItemType>>    ConsolationItems;                                  // 0x0350(0x0010)(Edit, BlueprintVisible)
	TArray<class UUWEPrimaryDataAssetBase*>       AssetToUnlock;                                     // 0x0360(0x0010)(Edit, BlueprintVisible)
	bool                                          ProvideConsolation;                                // 0x0370(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HasBeenUsed;                                       // 0x0371(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, SaveGame, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_372[0x6];                                      // 0x0372(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFMODEventInstance                     sfx_unopened_loop;                                 // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void Animate();
	bool CanInteract(class AActor* PlayerCharacter);
	void ExecuteUbergraph_BP_RecipeGainDataCard_Button(int32 EntryPoint);
	struct FInteractionInfo GetInteractionInfo(class AActor* HoverActor, class AActor* ForActor, class UPrimitiveComponent* HoverComponent, const struct FHitResult& HitResult);
	void Interact(class AController* Controller, class APawn* Pawn, const struct FHitResult& HitResult);
	void InteractClient(class AController* Controller, class APawn* Pawn, const struct FHitResult& HitResult);
	void InteractEnd(class AController* Controller, class APawn* Pawn);
	void InteractEndClient(class AController* Controller, class APawn* Pawn);
	void InteractEndServer(class AController* Controller, class APawn* Pawn);
	float InteractionDistance();
	void InteractServer(class AController* Controller, class APawn* Pawn, const struct FHitResult& HitResult);
	bool IsInteractDisabled(class AActor* HoverActor, class AActor* ForActor, float Distance, class UPrimitiveComponent* HoverComponent, const struct FHitResult& HitResult);
	void OnRep_HasBeenUsed();
	void ReceiveBeginPlay();
	void Timeline__FinishedFunc();
	void Timeline__UpdateFunc();
	void UpdateVisuals();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RecipeGainDataCard_Button_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RecipeGainDataCard_Button_C")
	}
	static class ABP_RecipeGainDataCard_Button_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RecipeGainDataCard_Button_C>();
	}
};
DUMPER7_ASSERTS_ABP_RecipeGainDataCard_Button_C;

}

