#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WindowPreview2x2

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_WindowPreview2x2.BP_WindowPreview2x2_C
// 0x0050 (0x0300 - 0x02B0)
class ABP_WindowPreview2x2_C final : public AActor
{
public:
	class UStaticMeshComponent*                   SM_Window_Exterior_FlatWall_Corner_90deg_A;        // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Window_Exterior_FlatWall_Corner_270deg_A;       // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Window_Exterior_FlatWall_Corner_180deg_A;       // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Window_Exterior_FlatWall_Corner_0deg_A;         // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Window_Glass_FlatWall_Corner_A;                 // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Window_Glass_FlatWall_Corner_90deg_A;           // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Window_Glass_FlatWall_Corner_270deg__A;         // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Window_Glass_FlatWall_Corner_180deg_A;          // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Scene;                                             // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_WindowPreview2x2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_WindowPreview2x2_C")
	}
	static class ABP_WindowPreview2x2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WindowPreview2x2_C>();
	}
};
DUMPER7_ASSERTS_ABP_WindowPreview2x2_C;

}

