#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WaterSlug

#include "Basic.hpp"

#include "UWERangeTracker_structs.hpp"


namespace SDK::Params
{

// Function BP_WaterSlug.BP_WaterSlug_C.BPOnEquipped
// 0x0001 (0x0001 - 0x0000)
struct BP_WaterSlug_C_BPOnEquipped final
{
public:
	bool                                          bFirstEquip;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_WaterSlug_C_BPOnEquipped;

// Function BP_WaterSlug.BP_WaterSlug_C.BPOnUnequipped
// 0x0008 (0x0008 - 0x0000)
struct BP_WaterSlug_C_BPOnUnequipped final
{
public:
	const class AActor*                           OldEquippedByActor;                                // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_WaterSlug_C_BPOnUnequipped;

// Function BP_WaterSlug.BP_WaterSlug_C.ExecuteUbergraph_BP_WaterSlug
// 0x00A8 (0x00A8 - 0x0000)
struct BP_WaterSlug_C_ExecuteUbergraph_BP_WaterSlug final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUWERangeTrackerRange                  K2Node_MakeStruct_UWERangeTrackerRange;            // 0x0028(0x0020)(NoDestructor)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUWERangeTrackerPeerRangeConfig        K2Node_MakeStruct_UWERangeTrackerPeerRangeConfig;  // 0x0050(0x0030)(NoDestructor)
	class UUWEListenPlayerInRange*                CallFunc_ListenPlayerInRange_ReturnValue;          // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bFirstEquip;                          // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsShowingSkeletal_ReturnValue;            // 0x008A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8B[0x5];                                       // 0x008B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	const class AActor*                           K2Node_Event_OldEquippedByActor;                   // 0x0090(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_WaterSlug_C_ExecuteUbergraph_BP_WaterSlug;

}

