#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_DeepStartLifepodClampArmReleasePoint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_DeepStartLifepodClampArmReleasePoint.BPC_DeepStartLifepodClampArmReleasePoint_C
// 0x0030 (0x0660 - 0x0630)
class UBPC_DeepStartLifepodClampArmReleasePoint_C final : public UStaticMeshComponent
{
public:
	uint8                                         Pad_628[0x8];                                      // 0x0628(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0630(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TMulticastInlineDelegate<void()>              OnClampReleased;                                   // 0x0638(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          ClampReleased;                                     // 0x0648(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, SaveGame, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_649[0x7];                                      // 0x0649(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     ReleasedMaterial;                                  // 0x0650(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UUWESaveHandle*                         Save_Handle;                                       // 0x0658(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPC_DeepStartLifepodClampArmReleasePoint(int32 EntryPoint);
	struct FInteractionInfo GetInteractionInfo(class AActor* HoverActor, class AActor* ForActor, class UPrimitiveComponent* HoverComponent, const struct FHitResult& HitResult);
	void Interact(class AController* Controller, class APawn* Pawn, const struct FHitResult& HitResult);
	void InteractClient(class AController* Controller, class APawn* Pawn, const struct FHitResult& HitResult);
	void InteractEnd(class AController* Controller, class APawn* Pawn);
	void InteractEndClient(class AController* Controller, class APawn* Pawn);
	void InteractEndServer(class AController* Controller, class APawn* Pawn);
	float InteractionDistance();
	void InteractServer(class AController* Controller, class APawn* Pawn, const struct FHitResult& HitResult);
	bool IsInteractDisabled(class AActor* HoverActor, class AActor* ForActor, float Distance, class UPrimitiveComponent* HoverComponent, const struct FHitResult& HitResult);
	void OnPostDeserialize();
	void OnPostSerialize();
	void OnPreDeserialize();
	void OnPreSerialize();
	void OnRep_ClampReleased();
	void ReceiveBeginPlay();
	void SetHandle(class UUWESaveHandle* InSaveHandle);
	void UpdateMaterials();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_DeepStartLifepodClampArmReleasePoint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_DeepStartLifepodClampArmReleasePoint_C")
	}
	static class UBPC_DeepStartLifepodClampArmReleasePoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_DeepStartLifepodClampArmReleasePoint_C>();
	}
};
DUMPER7_ASSERTS_UBPC_DeepStartLifepodClampArmReleasePoint_C;

}

