#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_PlayerStartUtils

#include "Basic.hpp"

#include "BPFL_PlayerStartUtils_classes.hpp"
#include "BPFL_PlayerStartUtils_parameters.hpp"


namespace SDK
{

// Function BPFL_PlayerStartUtils.BPFL_PlayerStartUtils_C.InitializeArrayOfItemsToSpawn
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<TSoftObjectPtr<class UUWEItemType>>&TargetArrayForCosts                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<class UUWECraftingRecipe*>&      ListOfBasePieces                                       (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32                                   BonusTitaniumForSculptsCount                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TArray<TSoftObjectPtr<class UUWEItemType>>*InitializedArray                                       (ConstParm, Parm, OutParm)

void UBPFL_PlayerStartUtils_C::InitializeArrayOfItemsToSpawn(const TArray<TSoftObjectPtr<class UUWEItemType>>& TargetArrayForCosts, TArray<class UUWECraftingRecipe*>& ListOfBasePieces, int32 BonusTitaniumForSculptsCount, class UObject* __WorldContext, TArray<TSoftObjectPtr<class UUWEItemType>>* InitializedArray)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_PlayerStartUtils_C", "InitializeArrayOfItemsToSpawn");

	Params::BPFL_PlayerStartUtils_C_InitializeArrayOfItemsToSpawn Parms{};

	Parms.TargetArrayForCosts = std::move(TargetArrayForCosts);
	Parms.ListOfBasePieces = std::move(ListOfBasePieces);
	Parms.BonusTitaniumForSculptsCount = BonusTitaniumForSculptsCount;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	ListOfBasePieces = std::move(Parms.ListOfBasePieces);

	if (InitializedArray != nullptr)
		*InitializedArray = std::move(Parms.InitializedArray);
}


// Function BPFL_PlayerStartUtils.BPFL_PlayerStartUtils_C.SpawnLockerAtNextOpenSpot
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NumLockersSpawned                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  DistBetweenLockersCM                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           PlayerActorToSpawnNear                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class ABP_FloatingLocker_Deprecated_C** LockerSpawned                                          (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPFL_PlayerStartUtils_C::SpawnLockerAtNextOpenSpot(int32 NumLockersSpawned, double DistBetweenLockersCM, class AActor* PlayerActorToSpawnNear, class UObject* __WorldContext, class ABP_FloatingLocker_Deprecated_C** LockerSpawned)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_PlayerStartUtils_C", "SpawnLockerAtNextOpenSpot");

	Params::BPFL_PlayerStartUtils_C_SpawnLockerAtNextOpenSpot Parms{};

	Parms.NumLockersSpawned = NumLockersSpawned;
	Parms.DistBetweenLockersCM = DistBetweenLockersCM;
	Parms.PlayerActorToSpawnNear = PlayerActorToSpawnNear;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (LockerSpawned != nullptr)
		*LockerSpawned = Parms.LockerSpawned;
}


// Function BPFL_PlayerStartUtils.BPFL_PlayerStartUtils_C.SpawnLockersWithSuppliesForYourBase
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           PlayerActorSelfReference                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TArray<class UUWECraftingRecipe*>&      ListOfBasePieces                                       (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32                                   BonusTitaniumForSculptsCount                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPFL_PlayerStartUtils_C::SpawnLockersWithSuppliesForYourBase(class AActor* PlayerActorSelfReference, TArray<class UUWECraftingRecipe*>& ListOfBasePieces, int32 BonusTitaniumForSculptsCount, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPFL_PlayerStartUtils_C", "SpawnLockersWithSuppliesForYourBase");

	Params::BPFL_PlayerStartUtils_C_SpawnLockersWithSuppliesForYourBase Parms{};

	Parms.PlayerActorSelfReference = PlayerActorSelfReference;
	Parms.ListOfBasePieces = std::move(ListOfBasePieces);
	Parms.BonusTitaniumForSculptsCount = BonusTitaniumForSculptsCount;
	Parms.__WorldContext = __WorldContext;

	UObject::ProcessEvent(Func, &Parms);

	ListOfBasePieces = std::move(Parms.ListOfBasePieces);
}

}

