#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_AnimEnum_CardnialDirection

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_AnimEnum_CardnialDirection.E_AnimEnum_CardnialDirection
// NumValues: 0x0007
enum class E_AnimEnum_CardnialDirection : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	NewEnumerator5                           = 5,
	E_AnimEnum_MAX                           = 6,
};

}

