#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_AI_CoralCrab_Dig

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_AI_CoralCrab_Dig.GA_AI_CoralCrab_Dig_C
// 0x0058 (0x0590 - 0x0538)
class UGA_AI_CoralCrab_Dig_C final : public UUWEGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0538(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         NumResourceToDigUp;                                // 0x0540(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LifeSpan;                                          // 0x0544(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxNumResourcesToDigUp;                            // 0x0548(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54C[0x4];                                      // 0x054C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_CoralCrab_C*                        BP_Coral_Crab;                                     // 0x0550(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Resource_to_Spawn;                                 // 0x0558(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         Index_0;                                           // 0x0560(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_564[0x4];                                      // 0x0564(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UUWERegionLootDataAsset> RegionLootData;                                    // 0x0568(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void DetermineNumberOfResourcesToDrop(int32 Max_Resources, int32* Number_To_Drop);
	void ExecuteUbergraph_GA_AI_CoralCrab_Dig(int32 EntryPoint);
	void K2_ActivateAbility();
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void OnBlendedIn_6C22F6344672100EAC9CF1BAC6DE6CDA();
	void OnBlendOut_6C22F6344672100EAC9CF1BAC6DE6CDA();
	void OnCancelled_6C22F6344672100EAC9CF1BAC6DE6CDA();
	void OnCompleted_6C22F6344672100EAC9CF1BAC6DE6CDA();
	void OnInterrupted_6C22F6344672100EAC9CF1BAC6DE6CDA();
	void OnLoaded_095A87D54BAC5417729649A118D71B78(class UObject* Loaded);
	void OnLoaded_4C41B2A340BAE841CBCC9DBA433AA916(TSubclassOf<class UObject> Loaded);
	void OnLoaded_B9A6B81A4C82DBA1ED52559C741DDC73(class UObject* Loaded);
	void OnNotifyBegin_CCBB6DBE46A48F3F886530994D530D2E();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_AI_CoralCrab_Dig_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_AI_CoralCrab_Dig_C")
	}
	static class UGA_AI_CoralCrab_Dig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_AI_CoralCrab_Dig_C>();
	}
};
DUMPER7_ASSERTS_UGA_AI_CoralCrab_Dig_C;

}

