#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_AI_FlashFish_Flash

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_AI_FlashFish_Flash.GA_AI_FlashFish_Flash_C
// 0x0020 (0x0558 - 0x0538)
class UGA_AI_FlashFish_Flash_C final : public UUWEGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0538(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<EObjectTypeQuery>                      Object_Types;                                      // 0x0540(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FActiveGameplayEffectHandle            LightStimulus;                                     // 0x0550(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_AI_FlashFish_Flash(int32 EntryPoint);
	void K2_ActivateAbility();
	void OnBlendedIn_E46EDD0643B75A94E9FB26AEF99A1D43();
	void OnBlendOut_E46EDD0643B75A94E9FB26AEF99A1D43();
	void OnCancelled_E46EDD0643B75A94E9FB26AEF99A1D43();
	void OnCompleted_E46EDD0643B75A94E9FB26AEF99A1D43();
	void OnInterrupted_E46EDD0643B75A94E9FB26AEF99A1D43();
	void OnNotifyBegin_0D33CA654CD839E7B89A7B96F85B7DC7();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_AI_FlashFish_Flash_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_AI_FlashFish_Flash_C")
	}
	static class UGA_AI_FlashFish_Flash_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_AI_FlashFish_Flash_C>();
	}
};
DUMPER7_ASSERTS_UGA_AI_FlashFish_Flash_C;

}

