#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_DelayedBoost

#include "Basic.hpp"

#include "GA_DelayedBoost_classes.hpp"
#include "GA_DelayedBoost_parameters.hpp"


namespace SDK
{

// Function GA_DelayedBoost.GA_DelayedBoost_C.ExecuteUbergraph_GA_DelayedBoost
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DelayedBoost_C::ExecuteUbergraph_GA_DelayedBoost(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DelayedBoost_C", "ExecuteUbergraph_GA_DelayedBoost");

	Params::GA_DelayedBoost_C_ExecuteUbergraph_GA_DelayedBoost Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DelayedBoost.GA_DelayedBoost_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_DelayedBoost_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DelayedBoost_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}

}

