#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_ManagePlayerSafety

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_ManagePlayerSafety.GA_ManagePlayerSafety_C
// 0x0018 (0x0550 - 0x0538)
class UGA_ManagePlayerSafety_C final : public UUWEGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0538(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FActiveGameplayEffectHandle            OxLowEffectHandle;                                 // 0x0540(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_WaitAttributeChangeThreshold* OxLowWaitTask;                                  // 0x0548(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_ManagePlayerSafety(int32 EntryPoint);
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnChange_4E13A5B7464F6704B0F6B58396D11063(bool bMatchesComparison, float CurrentValue);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_ManagePlayerSafety_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_ManagePlayerSafety_C")
	}
	static class UGA_ManagePlayerSafety_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_ManagePlayerSafety_C>();
	}
};
DUMPER7_ASSERTS_UGA_ManagePlayerSafety_C;

}

