#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameplayBehaviorSmartObjectsModule

#include "Basic.hpp"

#include "SmartObjectsModule_structs.hpp"
#include "SmartObjectsModule_classes.hpp"
#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class GameplayBehaviorSmartObjectsModule.GameplayBehaviorSmartObjectBehaviorDefinition
// 0x0008 (0x0030 - 0x0028)
class UGameplayBehaviorSmartObjectBehaviorDefinition final : public USmartObjectBehaviorDefinition
{
public:
	class UGameplayBehaviorConfig*                GameplayBehaviorConfig;                            // 0x0028(0x0008)(Edit, ExportObject, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GameplayBehaviorSmartObjectBehaviorDefinition")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameplayBehaviorSmartObjectBehaviorDefinition")
	}
	static class UGameplayBehaviorSmartObjectBehaviorDefinition* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameplayBehaviorSmartObjectBehaviorDefinition>();
	}
};
DUMPER7_ASSERTS_UGameplayBehaviorSmartObjectBehaviorDefinition;

// Class GameplayBehaviorSmartObjectsModule.AITask_UseGameplayBehaviorSmartObject
// 0x0078 (0x00E8 - 0x0070)
class UAITask_UseGameplayBehaviorSmartObject : public UAITask
{
public:
	TMulticastInlineDelegate<void()>              OnSucceeded;                                       // 0x0070(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, Protected, NativeAccessSpecifierProtected)
	TMulticastInlineDelegate<void()>              OnFailed;                                          // 0x0080(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, Protected, NativeAccessSpecifierProtected)
	TMulticastInlineDelegate<void()>              OnMoveToFailed;                                    // 0x0090(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, Protected, NativeAccessSpecifierProtected)
	class UAITask_MoveTo*                         MoveToTask;                                        // 0x00A0(0x0008)(ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected, TObjectPtr)
	class UGameplayBehavior*                      GameplayBehavior;                                  // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected, TObjectPtr)
	uint8                                         Pad_B0[0x38];                                      // 0x00B0(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UAITask_UseGameplayBehaviorSmartObject* MoveToAndUseSmartObjectWithGameplayBehavior(class AAIController* Controller, const struct FSmartObjectClaimHandle& ClaimHandle, bool bLockAILogic, ESmartObjectClaimPriority ClaimPriority);
	static class UAITask_UseGameplayBehaviorSmartObject* UseGameplayBehaviorSmartObject(class AAIController* Controller, class AActor* SmartObjectActor, class USmartObjectComponent* SmartObjectComponent, bool bLockAILogic);
	static class UAITask_UseGameplayBehaviorSmartObject* UseSmartObjectWithGameplayBehavior(class AAIController* Controller, const struct FSmartObjectClaimHandle& ClaimHandle, bool bLockAILogic, ESmartObjectClaimPriority ClaimPriority);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AITask_UseGameplayBehaviorSmartObject")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AITask_UseGameplayBehaviorSmartObject")
	}
	static class UAITask_UseGameplayBehaviorSmartObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAITask_UseGameplayBehaviorSmartObject>();
	}
};
DUMPER7_ASSERTS_UAITask_UseGameplayBehaviorSmartObject;

// Class GameplayBehaviorSmartObjectsModule.BTTask_FindAndUseGameplayBehaviorSmartObject
// 0x00B0 (0x0120 - 0x0070)
class UBTTask_FindAndUseGameplayBehaviorSmartObject final : public UBTTaskNode
{
public:
	struct FGameplayTagQuery                      ActivityRequirements;                              // 0x0070(0x0048)(Edit, Protected, NativeAccessSpecifierProtected)
	ESmartObjectClaimPriority                     ClaimPriority;                                     // 0x00B8(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEQSParametrizedQueryExecutionRequest  EQSRequest;                                        // 0x00C0(0x0048)(Edit, Protected, NativeAccessSpecifierProtected)
	float                                         Radius;                                            // 0x0108(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_10C[0x14];                                     // 0x010C(0x0014)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BTTask_FindAndUseGameplayBehaviorSmartObject")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTTask_FindAndUseGameplayBehaviorSmartObject")
	}
	static class UBTTask_FindAndUseGameplayBehaviorSmartObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTTask_FindAndUseGameplayBehaviorSmartObject>();
	}
};
DUMPER7_ASSERTS_UBTTask_FindAndUseGameplayBehaviorSmartObject;

// Class GameplayBehaviorSmartObjectsModule.GameplayBehaviorSmartObjectsBlueprintFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UGameplayBehaviorSmartObjectsBlueprintFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static bool UseGameplayBehaviorSmartObject(class AActor* Avatar, class AActor* SmartObject);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("GameplayBehaviorSmartObjectsBlueprintFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameplayBehaviorSmartObjectsBlueprintFunctionLibrary")
	}
	static class UGameplayBehaviorSmartObjectsBlueprintFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameplayBehaviorSmartObjectsBlueprintFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UGameplayBehaviorSmartObjectsBlueprintFunctionLibrary;

}

