#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameSettings

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct GameSettings.GameSettingFilterState
// 0x03A0 (0x03A0 - 0x0000)
struct FGameSettingFilterState final
{
public:
	bool                                          bIncludeDisabled;                                  // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIncludeHidden;                                    // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIncludeResetable;                                 // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIncludeNestedPages;                               // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x37C];                                      // 0x0004(0x037C)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UGameSetting*>                   SettingRootList;                                   // 0x0380(0x0010)(ZeroConstructor, UObjectWrapper, NativeAccessSpecifierPrivate, TObjectPtr)
	TArray<class UGameSetting*>                   SettingAllowList;                                  // 0x0390(0x0010)(ZeroConstructor, UObjectWrapper, NativeAccessSpecifierPrivate, TObjectPtr)
};
DUMPER7_ASSERTS_FGameSettingFilterState;

// ScriptStruct GameSettings.GameSettingClassExtensions
// 0x0010 (0x0010 - 0x0000)
struct FGameSettingClassExtensions final
{
public:
	TArray<TSoftClassPtr<class UClass>>           Extensions;                                        // 0x0000(0x0010)(Edit, ZeroConstructor, UObjectWrapper, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGameSettingClassExtensions;

// ScriptStruct GameSettings.GameSettingNameExtensions
// 0x0018 (0x0018 - 0x0000)
struct FGameSettingNameExtensions final
{
public:
	bool                                          bIncludeClassDefaultExtensions;                    // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<TSoftClassPtr<class UClass>>           Extensions;                                        // 0x0008(0x0010)(Edit, ZeroConstructor, UObjectWrapper, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGameSettingNameExtensions;

}

