#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Carryables_HardPoint_Detach

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Carryables_HardPoint_Detach.GC_Carryables_HardPoint_Detach_C
// 0x0000 (0x04F0 - 0x04F0)
class UGC_Carryables_HardPoint_Detach_C final : public UUWEGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_Carryables_HardPoint_Detach_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_Carryables_HardPoint_Detach_C")
	}
	static class UGC_Carryables_HardPoint_Detach_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_Carryables_HardPoint_Detach_C>();
	}
};
DUMPER7_ASSERTS_UGC_Carryables_HardPoint_Detach_C;

}

