#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_EMTPointOxygenator

#include "Basic.hpp"

#include "GC_EMTPointOxygenator_classes.hpp"
#include "GC_EMTPointOxygenator_parameters.hpp"


namespace SDK
{

// Function GC_EMTPointOxygenator.GC_EMTPointOxygenator_C.ExecuteUbergraph_GC_EMTPointOxygenator
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGC_EMTPointOxygenator_C::ExecuteUbergraph_GC_EMTPointOxygenator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_EMTPointOxygenator_C", "ExecuteUbergraph_GC_EMTPointOxygenator");

	Params::GC_EMTPointOxygenator_C_ExecuteUbergraph_GC_EMTPointOxygenator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GC_EMTPointOxygenator.GC_EMTPointOxygenator_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AGC_EMTPointOxygenator_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_EMTPointOxygenator_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

