#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_PlayeDoublePingLooping

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_PlayeDoublePingLooping.GC_PlayeDoublePingLooping_C
// 0x0008 (0x1740 - 0x1738)
class AGC_PlayeDoublePingLooping_C final : public AUWEGameplayCueNotify_Looping
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1738(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GC_PlayeDoublePingLooping(int32 EntryPoint);
	void OnLoopingStart(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_PlayeDoublePingLooping_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_PlayeDoublePingLooping_C")
	}
	static class AGC_PlayeDoublePingLooping_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_PlayeDoublePingLooping_C>();
	}
};
DUMPER7_ASSERTS_AGC_PlayeDoublePingLooping_C;

}

