#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Player_Downed

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Player_Downed.GC_Player_Downed_C
// 0x0000 (0x1738 - 0x1738)
class AGC_Player_Downed_C final : public AUWEGameplayCueNotify_Looping
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_Player_Downed_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_Player_Downed_C")
	}
	static class AGC_Player_Downed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Player_Downed_C>();
	}
};
DUMPER7_ASSERTS_AGC_Player_Downed_C;

}

