#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_ScannerRays

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_ScannerRays.GC_ScannerRays_C
// 0x0018 (0x1750 - 0x1738)
class AGC_ScannerRays_C final : public AUWEGameplayCueNotify_Looping
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1738(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Rays;                                              // 0x1740(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         RaysTemplate;                                      // 0x1748(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GC_ScannerRays(int32 EntryPoint);
	void OnLoopingStart(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);
	void OnRemoval(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_ScannerRays_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_ScannerRays_C")
	}
	static class AGC_ScannerRays_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_ScannerRays_C>();
	}
};
DUMPER7_ASSERTS_AGC_ScannerRays_C;

}

