#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_TadpoleEnergyDrain

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_TadpoleEnergyDrain.GC_TadpoleEnergyDrain_C
// 0x0030 (0x1768 - 0x1738)
class AGC_TadpoleEnergyDrain_C final : public AUWEGameplayCueNotify_Looping
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1738(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USpotLightComponent*                    SpotLight_L;                                       // 0x1740(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight_R;                                       // 0x1748(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_Strength_2388211A455359B63B8EE1B4479C47D2; // 0x1750(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline__Direction_2388211A455359B63B8EE1B4479C47D2; // 0x1754(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1755[0x3];                                     // 0x1755(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline;                                          // 0x1758(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ABP_Tadpole_C*                          As_BP_Tadpole;                                     // 0x1760(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GC_TadpoleEnergyDrain(int32 EntryPoint);
	void OnLoopingStart(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);
	void OnRemoval(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);
	void PowerDrainVFX();
	void Timeline__FinishedFunc();
	void Timeline__UpdateFunc();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_TadpoleEnergyDrain_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_TadpoleEnergyDrain_C")
	}
	static class AGC_TadpoleEnergyDrain_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_TadpoleEnergyDrain_C>();
	}
};
DUMPER7_ASSERTS_AGC_TadpoleEnergyDrain_C;

}

