#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Wakemaker_Lights

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Wakemaker_Lights.GC_Wakemaker_Lights_C
// 0x0028 (0x1760 - 0x1738)
class AGC_Wakemaker_Lights_C final : public AUWEGameplayCueNotify_Looping
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1738(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Lightlense5;                                       // 0x1740(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Lightlense2;                                       // 0x1748(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight_L;                                       // 0x1750(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight_R;                                       // 0x1758(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GC_Wakemaker_Lights(int32 EntryPoint);
	void OnLoopingStart(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);
	void OnRemoval(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_Wakemaker_Lights_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_Wakemaker_Lights_C")
	}
	static class AGC_Wakemaker_Lights_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Wakemaker_Lights_C>();
	}
};
DUMPER7_ASSERTS_AGC_Wakemaker_Lights_C;

}

