#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_BurstStimulusSphere_Tiny

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_BurstStimulusSphere_Tiny.GE_BurstStimulusSphere_Tiny_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_BurstStimulusSphere_Tiny_C : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_BurstStimulusSphere_Tiny_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_BurstStimulusSphere_Tiny_C")
	}
	static class UGE_BurstStimulusSphere_Tiny_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_BurstStimulusSphere_Tiny_C>();
	}
};
DUMPER7_ASSERTS_UGE_BurstStimulusSphere_Tiny_C;

}

