#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MercunaMover

#include "Basic.hpp"

#include "Mover_structs.hpp"


namespace SDK::Params
{

// Function MercunaMover.MerMoverComponentAdapter.OnMovementModeChanged
// 0x0010 (0x0010 - 0x0000)
struct MerMoverComponentAdapter_OnMovementModeChanged final
{
public:
	class FName                                   PreviousMovementModeName;                          // 0x0000(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NewMovementModeName;                               // 0x0008(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MerMoverComponentAdapter_OnMovementModeChanged;

// Function MercunaMover.MerMoverComponentAdapter.OnPreSimTick
// 0x0020 (0x0020 - 0x0000)
struct MerMoverComponentAdapter_OnPreSimTick final
{
public:
	struct FMoverTimeStep                         TimeStep;                                          // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	struct FMoverInputCmdContext                  InputCmd;                                          // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MerMoverComponentAdapter_OnPreSimTick;

}

