#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: oldABP_TwinEels_001

#include "Basic.hpp"

#include "oldABP_TwinEels_001_classes.hpp"
#include "oldABP_TwinEels_001_parameters.hpp"


namespace SDK
{

// Function oldABP_TwinEels_001.oldABP_TwinEels_001_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UoldABP_TwinEels_001_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("oldABP_TwinEels_001_C", "AnimGraph");

	Params::oldABP_TwinEels_001_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function oldABP_TwinEels_001.oldABP_TwinEels_001_C.AnimNotify_EndAttack
// (BlueprintCallable, BlueprintEvent)

void UoldABP_TwinEels_001_C::AnimNotify_EndAttack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("oldABP_TwinEels_001_C", "AnimNotify_EndAttack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function oldABP_TwinEels_001.oldABP_TwinEels_001_C.BeginAttack
// (BlueprintCallable, BlueprintEvent)

void UoldABP_TwinEels_001_C::BeginAttack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("oldABP_TwinEels_001_C", "BeginAttack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function oldABP_TwinEels_001.oldABP_TwinEels_001_C.BlueprintBeginPlay
// (Event, Public, BlueprintEvent)

void UoldABP_TwinEels_001_C::BlueprintBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("oldABP_TwinEels_001_C", "BlueprintBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function oldABP_TwinEels_001.oldABP_TwinEels_001_C.EndAttack
// (BlueprintCallable, BlueprintEvent)

void UoldABP_TwinEels_001_C::EndAttack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("oldABP_TwinEels_001_C", "EndAttack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function oldABP_TwinEels_001.oldABP_TwinEels_001_C.EvaluateGraphExposedInputs_ExecuteUbergraph_oldABP_TwinEels_001_AnimGraphNode_TransitionResult_F9FAA7CD4757E446189F119E24902181
// (BlueprintEvent)

void UoldABP_TwinEels_001_C::EvaluateGraphExposedInputs_ExecuteUbergraph_oldABP_TwinEels_001_AnimGraphNode_TransitionResult_F9FAA7CD4757E446189F119E24902181()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("oldABP_TwinEels_001_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_oldABP_TwinEels_001_AnimGraphNode_TransitionResult_F9FAA7CD4757E446189F119E24902181");

	UObject::ProcessEvent(Func, nullptr);
}


// Function oldABP_TwinEels_001.oldABP_TwinEels_001_C.ExecuteUbergraph_oldABP_TwinEels_001
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UoldABP_TwinEels_001_C::ExecuteUbergraph_oldABP_TwinEels_001(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("oldABP_TwinEels_001_C", "ExecuteUbergraph_oldABP_TwinEels_001");

	Params::oldABP_TwinEels_001_C_ExecuteUbergraph_oldABP_TwinEels_001 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

