#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWEBiomods

#include "Basic.hpp"

#include "UWEBiomods_classes.hpp"
#include "UWEBiomods_parameters.hpp"


namespace SDK
{

// Function UWEBiomods.UWEBioAbilityData.GetAllBioAbilityData
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// bool                                    bOnlyUnlocked                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class UUWEBioAbilityData*>       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class UUWEBioAbilityData*> UUWEBioAbilityData::GetAllBioAbilityData(bool bOnlyUnlocked, class UObject* WorldContextObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UWEBioAbilityData", "GetAllBioAbilityData");

	Params::UWEBioAbilityData_GetAllBioAbilityData Parms{};

	Parms.bOnlyUnlocked = bOnlyUnlocked;
	Parms.WorldContextObject = WorldContextObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioAbilityData.GetBioAbilitiesForActor
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// const class AActor*                     Actor                                                  (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class UGameplayAbility*>         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class UGameplayAbility*> UUWEBioAbilityData::GetBioAbilitiesForActor(const class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UWEBioAbilityData", "GetBioAbilitiesForActor");

	Params::UWEBioAbilityData_GetBioAbilitiesForActor Parms{};

	Parms.Actor = Actor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioAbilityData.GetBioAbilityDataFromAbility
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// const TSubclassOf<class UGameplayAbility>AbilityClass                                           (ConstParm, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UUWEBioAbilityData*               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UUWEBioAbilityData* UUWEBioAbilityData::GetBioAbilityDataFromAbility(const TSubclassOf<class UGameplayAbility> AbilityClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UWEBioAbilityData", "GetBioAbilityDataFromAbility");

	Params::UWEBioAbilityData_GetBioAbilityDataFromAbility Parms{};

	Parms.AbilityClass = AbilityClass;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioAbilityData.GetBioAbilityDataFromAbilityTag
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UUWEBioAbilityData*               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UUWEBioAbilityData* UUWEBioAbilityData::GetBioAbilityDataFromAbilityTag(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UWEBioAbilityData", "GetBioAbilityDataFromAbilityTag");

	Params::UWEBioAbilityData_GetBioAbilityDataFromAbilityTag Parms{};

	Parms.Tag = std::move(Tag);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioAbilityData.GetMissingRequiredBioScans
// (Final, Native, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class UUWEBioScanData*>          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class UUWEBioScanData*> UUWEBioAbilityData::GetMissingRequiredBioScans(class UObject* WorldContextObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityData", "GetMissingRequiredBioScans");

	Params::UWEBioAbilityData_GetMissingRequiredBioScans Parms{};

	Parms.WorldContextObject = WorldContextObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioAbilityData.GetUnlockedRequiredBioScans
// (Final, Native, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class UUWEBioScanData*>          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class UUWEBioScanData*> UUWEBioAbilityData::GetUnlockedRequiredBioScans(class UObject* WorldContextObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityData", "GetUnlockedRequiredBioScans");

	Params::UWEBioAbilityData_GetUnlockedRequiredBioScans Parms{};

	Parms.WorldContextObject = WorldContextObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioAbilityData.GetUnlockState
// (Native, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class APlayerState*                     PlayerState                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EUnlockState                            ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

EUnlockState UUWEBioAbilityData::GetUnlockState(class APlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityData", "GetUnlockState");

	Params::UWEBioAbilityData_GetUnlockState Parms{};

	Parms.PlayerState = PlayerState;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioAbilityData.IsCrafted
// (Final, Native, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUWEBioAbilityData::IsCrafted(class UObject* WorldContextObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityData", "IsCrafted");

	Params::UWEBioAbilityData_IsCrafted Parms{};

	Parms.WorldContextObject = WorldContextObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioAbilityData.IsUnlocked
// (Final, Native, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUWEBioAbilityData::IsUnlocked(class UObject* WorldContextObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityData", "IsUnlocked");

	Params::UWEBioAbilityData_IsUnlocked Parms{};

	Parms.WorldContextObject = WorldContextObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioAbilityData.IsActiveBioAbility
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUWEBioAbilityData::IsActiveBioAbility() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityData", "IsActiveBioAbility");

	Params::UWEBioAbilityData_IsActiveBioAbility Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioAbilityViewModel.InstallBioAbility
// (Final, Native, Public, BlueprintCallable)

void UUWEBioAbilityViewModel::InstallBioAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityViewModel", "InstallBioAbility");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBioAbilityViewModel.OnRecipePinned
// (Final, Native, Protected)
// Parameters:
// class UUWEPrimaryDataAssetBase*         Recipe                                                 (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBioAbilityViewModel::OnRecipePinned(class UUWEPrimaryDataAssetBase* Recipe)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityViewModel", "OnRecipePinned");

	Params::UWEBioAbilityViewModel_OnRecipePinned Parms{};

	Parms.Recipe = Recipe;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBioAbilityViewModel.OnRecipeUnpinned
// (Final, Native, Protected)
// Parameters:
// class UUWEPrimaryDataAssetBase*         Recipe                                                 (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBioAbilityViewModel::OnRecipeUnpinned(class UUWEPrimaryDataAssetBase* Recipe)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityViewModel", "OnRecipeUnpinned");

	Params::UWEBioAbilityViewModel_OnRecipeUnpinned Parms{};

	Parms.Recipe = Recipe;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBioAbilityViewModel.Setup
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UUWEBioAbilityData*               InAbilityData                                          (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AUWEBioLab*                       biolab                                                 (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UUWEBiomodCrafterInteractionComponent*InteractionComponent                                   (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AActor*                           BioAbilityOwner                                        (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInIsInstalled                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInAvailabilityOverriden                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBioAbilityViewModel::Setup(class UUWEBioAbilityData* InAbilityData, class AUWEBioLab* biolab, class UUWEBiomodCrafterInteractionComponent* InteractionComponent, class AActor* BioAbilityOwner, bool bInIsInstalled, bool bInAvailabilityOverriden)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityViewModel", "Setup");

	Params::UWEBioAbilityViewModel_Setup Parms{};

	Parms.InAbilityData = InAbilityData;
	Parms.biolab = biolab;
	Parms.InteractionComponent = InteractionComponent;
	Parms.BioAbilityOwner = BioAbilityOwner;
	Parms.bInIsInstalled = bInIsInstalled;
	Parms.bInAvailabilityOverriden = bInAvailabilityOverriden;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBioAbilityViewModel.TrySetRecipePinned
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bNewValue                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBioAbilityViewModel::TrySetRecipePinned(bool bNewValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityViewModel", "TrySetRecipePinned");

	Params::UWEBioAbilityViewModel_TrySetRecipePinned Parms{};

	Parms.bNewValue = bNewValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBioAbilityViewModel.UninstallBioAbility
// (Final, Native, Public, BlueprintCallable)

void UUWEBioAbilityViewModel::UninstallBioAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityViewModel", "UninstallBioAbility");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBioAbilityViewModel.GetCooldownFraction
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UUWEBioAbilityViewModel::GetCooldownFraction(class UObject* WorldContextObject) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityViewModel", "GetCooldownFraction");

	Params::UWEBioAbilityViewModel_GetCooldownFraction Parms{};

	Parms.WorldContextObject = WorldContextObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioAbilityViewModel.GetRemainingCooldownSeconds
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UUWEBioAbilityViewModel::GetRemainingCooldownSeconds(class UObject* WorldContextObject) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioAbilityViewModel", "GetRemainingCooldownSeconds");

	Params::UWEBioAbilityViewModel_GetRemainingCooldownSeconds Parms{};

	Parms.WorldContextObject = WorldContextObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioLab.CloseUI
// (Final, Native, Private)

void AUWEBioLab::CloseUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioLab", "CloseUI");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBioLab.OnWidgetPopped
// (Final, Native, Private)
// Parameters:
// EUWEWindowManagerLayer                  LayerId                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bIsLast                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TSubclassOf<class UCommonActivatableWidget>Class_0                                                (Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AUWEBioLab::OnWidgetPopped(EUWEWindowManagerLayer LayerId, bool bIsLast, TSubclassOf<class UCommonActivatableWidget> Class_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioLab", "OnWidgetPopped");

	Params::UWEBioLab_OnWidgetPopped Parms{};

	Parms.LayerId = LayerId;
	Parms.bIsLast = bIsLast;
	Parms.Class_0 = Class_0;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBioLabViewModel.Disconnect
// (Final, Native, Public, BlueprintCallable)

void UUWEBioLabViewModel::Disconnect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioLabViewModel", "Disconnect");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBioLabViewModel.OnAbilityGiven
// (Final, Native, Private, HasOutParams)
// Parameters:
// const class UUWEAbilitySystemComponent* ASC                                                    (ConstParm, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FGameplayAbilitySpecHandle&AbilitySpecHandle                                      (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBioLabViewModel::OnAbilityGiven(const class UUWEAbilitySystemComponent* ASC, const struct FGameplayAbilitySpecHandle& AbilitySpecHandle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioLabViewModel", "OnAbilityGiven");

	Params::UWEBioLabViewModel_OnAbilityGiven Parms{};

	Parms.ASC = ASC;
	Parms.AbilitySpecHandle = std::move(AbilitySpecHandle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBioLabViewModel.OnAbilityRemoved
// (Final, Native, Private, HasOutParams)
// Parameters:
// const class UUWEAbilitySystemComponent* ASC                                                    (ConstParm, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FGameplayAbilitySpecHandle&AbilitySpecHandle                                      (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBioLabViewModel::OnAbilityRemoved(const class UUWEAbilitySystemComponent* ASC, const struct FGameplayAbilitySpecHandle& AbilitySpecHandle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioLabViewModel", "OnAbilityRemoved");

	Params::UWEBioLabViewModel_OnAbilityRemoved Parms{};

	Parms.ASC = ASC;
	Parms.AbilitySpecHandle = std::move(AbilitySpecHandle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBiomodCrafterInteractionComponent.ServerInstallBiomod
// (Net, NetReliable, Native, Event, Public, NetServer)
// Parameters:
// class UUWEBioAbilityData*               AbilityData                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBiomodCrafterInteractionComponent::ServerInstallBiomod(class UUWEBioAbilityData* AbilityData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBiomodCrafterInteractionComponent", "ServerInstallBiomod");

	Params::UWEBiomodCrafterInteractionComponent_ServerInstallBiomod Parms{};

	Parms.AbilityData = AbilityData;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBiomodCrafterInteractionComponent.ServerUninstallBiomod
// (Net, NetReliable, Native, Event, Public, NetServer)
// Parameters:
// class UUWEBioAbilityData*               AbilityData                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBiomodCrafterInteractionComponent::ServerUninstallBiomod(class UUWEBioAbilityData* AbilityData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBiomodCrafterInteractionComponent", "ServerUninstallBiomod");

	Params::UWEBiomodCrafterInteractionComponent_ServerUninstallBiomod Parms{};

	Parms.AbilityData = AbilityData;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBiomodHUDViewModel.TryGetBiomodHUDViewModel
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          WorldContext                                           (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UUWEBiomodHUDViewModel*           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UUWEBiomodHUDViewModel* UUWEBiomodHUDViewModel::TryGetBiomodHUDViewModel(class UObject* WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UWEBiomodHUDViewModel", "TryGetBiomodHUDViewModel");

	Params::UWEBiomodHUDViewModel_TryGetBiomodHUDViewModel Parms{};

	Parms.WorldContext = WorldContext;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBiomodHUDViewModel.DisplayBiomodActiveState
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UGameplayAbility*                 GameplayAbility                                        (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bIsActive                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBiomodHUDViewModel::DisplayBiomodActiveState(class UGameplayAbility* GameplayAbility, bool bIsActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBiomodHUDViewModel", "DisplayBiomodActiveState");

	Params::UWEBiomodHUDViewModel_DisplayBiomodActiveState Parms{};

	Parms.GameplayAbility = GameplayAbility;
	Parms.bIsActive = bIsActive;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBiomodHUDViewModel.OnAbilityActivated
// (Final, Native, Private)
// Parameters:
// class UGameplayAbility*                 GameplayAbility                                        (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBiomodHUDViewModel::OnAbilityActivated(class UGameplayAbility* GameplayAbility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBiomodHUDViewModel", "OnAbilityActivated");

	Params::UWEBiomodHUDViewModel_OnAbilityActivated Parms{};

	Parms.GameplayAbility = GameplayAbility;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBiomodHUDViewModel.OnAbilityCommit
// (Final, Native, Private)
// Parameters:
// class UGameplayAbility*                 GameplayAbility                                        (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBiomodHUDViewModel::OnAbilityCommit(class UGameplayAbility* GameplayAbility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBiomodHUDViewModel", "OnAbilityCommit");

	Params::UWEBiomodHUDViewModel_OnAbilityCommit Parms{};

	Parms.GameplayAbility = GameplayAbility;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBiomodHUDViewModel.OnAbilityEnded
// (Final, Native, Private)
// Parameters:
// class UGameplayAbility*                 GameplayAbility                                        (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBiomodHUDViewModel::OnAbilityEnded(class UGameplayAbility* GameplayAbility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBiomodHUDViewModel", "OnAbilityEnded");

	Params::UWEBiomodHUDViewModel_OnAbilityEnded Parms{};

	Parms.GameplayAbility = GameplayAbility;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBiomodHUDViewModel.OnAbilityGiven
// (Final, Native, Private, HasOutParams)
// Parameters:
// const class UUWEAbilitySystemComponent* ASC                                                    (ConstParm, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FGameplayAbilitySpecHandle&AbilitySpecHandle                                      (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBiomodHUDViewModel::OnAbilityGiven(const class UUWEAbilitySystemComponent* ASC, const struct FGameplayAbilitySpecHandle& AbilitySpecHandle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBiomodHUDViewModel", "OnAbilityGiven");

	Params::UWEBiomodHUDViewModel_OnAbilityGiven Parms{};

	Parms.ASC = ASC;
	Parms.AbilitySpecHandle = std::move(AbilitySpecHandle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBiomodHUDViewModel.OnAbilityRemoved
// (Final, Native, Private, HasOutParams)
// Parameters:
// const class UUWEAbilitySystemComponent* ASC                                                    (ConstParm, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FGameplayAbilitySpecHandle&AbilitySpecHandle                                      (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEBiomodHUDViewModel::OnAbilityRemoved(const class UUWEAbilitySystemComponent* ASC, const struct FGameplayAbilitySpecHandle& AbilitySpecHandle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBiomodHUDViewModel", "OnAbilityRemoved");

	Params::UWEBiomodHUDViewModel_OnAbilityRemoved Parms{};

	Parms.ASC = ASC;
	Parms.AbilitySpecHandle = std::move(AbilitySpecHandle);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBiomodHUDViewModel.OnLocalClientReady
// (Final, Native, Private)

void UUWEBiomodHUDViewModel::OnLocalClientReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBiomodHUDViewModel", "OnLocalClientReady");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWEBiomods.UWEBiomodHUDViewModel.GetViewModelForAbility
// (Final, Native, Private, Const)
// Parameters:
// const class UGameplayAbility*           GameplayAbility                                        (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UUWEBioAbilityViewModel*          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UUWEBioAbilityViewModel* UUWEBiomodHUDViewModel::GetViewModelForAbility(const class UGameplayAbility* GameplayAbility) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBiomodHUDViewModel", "GetViewModelForAbility");

	Params::UWEBiomodHUDViewModel_GetViewModelForAbility Parms{};

	Parms.GameplayAbility = GameplayAbility;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBiomodStatics.GetInstalledAbilities
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// const class AActor*                     Actor                                                  (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class UUWEBioAbilityData*>       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class UUWEBioAbilityData*> UUWEBiomodStatics::GetInstalledAbilities(const class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UWEBiomodStatics", "GetInstalledAbilities");

	Params::UWEBiomodStatics_GetInstalledAbilities Parms{};

	Parms.Actor = Actor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBiomodStatics.GetInstalledPassiveBioAbilities
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// const class AActor*                     Actor                                                  (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class UUWEBioAbilityData*>       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class UUWEBioAbilityData*> UUWEBiomodStatics::GetInstalledPassiveBioAbilities(const class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UWEBiomodStatics", "GetInstalledPassiveBioAbilities");

	Params::UWEBiomodStatics_GetInstalledPassiveBioAbilities Parms{};

	Parms.Actor = Actor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBiomodStatics.HasActiveBioAbility
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// const class AActor*                     Actor                                                  (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUWEBiomodStatics::HasActiveBioAbility(const class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UWEBiomodStatics", "HasActiveBioAbility");

	Params::UWEBiomodStatics_HasActiveBioAbility Parms{};

	Parms.Actor = Actor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBiomodStatics.HasBioAbility
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// const class UUWEBioAbilityData*         BioAbilityData                                         (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class AActor*                     Actor                                                  (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUWEBiomodStatics::HasBioAbility(const class UUWEBioAbilityData* BioAbilityData, const class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UWEBiomodStatics", "HasBioAbility");

	Params::UWEBiomodStatics_HasBioAbility Parms{};

	Parms.BioAbilityData = BioAbilityData;
	Parms.Actor = Actor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBiomodStatics.HasBioScanCapability
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class APlayerState*                     PS                                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUWEBiomodStatics::HasBioScanCapability(class APlayerState* PS)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UWEBiomodStatics", "HasBioScanCapability");

	Params::UWEBiomodStatics_HasBioScanCapability Parms{};

	Parms.PS = PS;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBiomodStatics.ShouldIgnoreUnlockBiomodRequirements
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// const class UObject*                    WorldContextObject                                     (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUWEBiomodStatics::ShouldIgnoreUnlockBiomodRequirements(const class UObject* WorldContextObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UWEBiomodStatics", "ShouldIgnoreUnlockBiomodRequirements");

	Params::UWEBiomodStatics_ShouldIgnoreUnlockBiomodRequirements Parms{};

	Parms.WorldContextObject = WorldContextObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEBiomods.UWEBioScanData.GetUnlockState
// (Native, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class APlayerState*                     PlayerState                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EUnlockState                            ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

EUnlockState UUWEBioScanData::GetUnlockState(class APlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEBioScanData", "GetUnlockState");

	Params::UWEBioScanData_GetUnlockState Parms{};

	Parms.PlayerState = PlayerState;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

