#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWEFeedback

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class UWEFeedback.UWEFeedbackSubsystem
// 0x0038 (0x0068 - 0x0030)
class UUWEFeedbackSubsystem final : public UGameInstanceSubsystem
{
public:
	bool                                          bUploadSupportingFiles;                            // 0x0030(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class UTexture2D* ScreenshotTexture)> ScreenshotRequestHandle;     // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x20];                                      // 0x0048(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void RequestScreenshot(bool ShowUI);
	void SubmitFeedback(class APlayerController* PC, const class FString& Sentiment, const class FString& Response, const class FString& CustomMessage);
	void UploadSupportingFiles(class APlayerController* PC, const class FString& Sentiment, const class FString& Response, const class FString& CustomMessage);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UWEFeedbackSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UWEFeedbackSubsystem")
	}
	static class UUWEFeedbackSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUWEFeedbackSubsystem>();
	}
};
DUMPER7_ASSERTS_UUWEFeedbackSubsystem;

}

