#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWESonar

#include "Basic.hpp"

#include "UWESonar_classes.hpp"
#include "UWESonar_parameters.hpp"


namespace SDK
{

// Function UWESonar.UWEMultiplayerHostedSessionViewModel.SetErrorText
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FText&                      Error                                                  (Parm, NativeAccessSpecifierPublic)

void UUWEMultiplayerHostedSessionViewModel::SetErrorText(const class FText& Error)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEMultiplayerHostedSessionViewModel", "SetErrorText");

	Params::UWEMultiplayerHostedSessionViewModel_SetErrorText Parms{};

	Parms.Error = std::move(Error);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWEMultiplayerHostedSessionViewModel.SetInviteOnly
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    NewInviteOnly                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEMultiplayerHostedSessionViewModel::SetInviteOnly(bool NewInviteOnly)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEMultiplayerHostedSessionViewModel", "SetInviteOnly");

	Params::UWEMultiplayerHostedSessionViewModel_SetInviteOnly Parms{};

	Parms.NewInviteOnly = NewInviteOnly;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWEMultiplayerHostedSessionViewModel.TriggerHostGameRequest
// (Final, Native, Public, BlueprintCallable)

void UUWEMultiplayerHostedSessionViewModel::TriggerHostGameRequest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEMultiplayerHostedSessionViewModel", "TriggerHostGameRequest");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWEOnlineSessionSubsystem.HostSessionAsync
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class APlayerController*                HostingPlayerController                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    AllowAllFriends                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    GameModeAlias                                          (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    ServerName                                             (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    SaveSlot                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    SaveCheckpoint                                         (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEOnlineSessionSubsystem::HostSessionAsync(class APlayerController* HostingPlayerController, bool AllowAllFriends, const class FString& GameModeAlias, const class FString& ServerName, const class FString& SaveSlot, const class FString& SaveCheckpoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEOnlineSessionSubsystem", "HostSessionAsync");

	Params::UWEOnlineSessionSubsystem_HostSessionAsync Parms{};

	Parms.HostingPlayerController = HostingPlayerController;
	Parms.AllowAllFriends = AllowAllFriends;
	Parms.GameModeAlias = std::move(GameModeAlias);
	Parms.ServerName = std::move(ServerName);
	Parms.SaveSlot = std::move(SaveSlot);
	Parms.SaveCheckpoint = std::move(SaveCheckpoint);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarCommunicationComponent.ServerSetSonarInfoForClient
// (Net, NetReliable, Native, Event, Public, NetServer)
// Parameters:
// class APlayerController*                PlayerController                                       (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    SonarPlayerId                                          (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    PlatformUserId                                         (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    PlatformProvider                                       (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWESonarCommunicationComponent::ServerSetSonarInfoForClient(class APlayerController* PlayerController, const class FString& SonarPlayerId, const class FString& PlatformUserId, const class FString& PlatformProvider)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarCommunicationComponent", "ServerSetSonarInfoForClient");

	Params::UWESonarCommunicationComponent_ServerSetSonarInfoForClient Parms{};

	Parms.PlayerController = PlayerController;
	Parms.SonarPlayerId = std::move(SonarPlayerId);
	Parms.PlatformUserId = std::move(PlatformUserId);
	Parms.PlatformProvider = std::move(PlatformProvider);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarFriendsSubsystem.ConsumePendingNewIncomingInviteCount
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UUWESonarFriendsSubsystem::ConsumePendingNewIncomingInviteCount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarFriendsSubsystem", "ConsumePendingNewIncomingInviteCount");

	Params::UWESonarFriendsSubsystem_ConsumePendingNewIncomingInviteCount Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWESonar.UWESonarFriendsSubsystem.GetPlatformLogo
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const TSoftObjectPtr<class UTexture2D>  ReturnValue                                            (ConstParm, Parm, OutParm, ReturnParm, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const TSoftObjectPtr<class UTexture2D> UUWESonarFriendsSubsystem::GetPlatformLogo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarFriendsSubsystem", "GetPlatformLogo");

	Params::UWESonarFriendsSubsystem_GetPlatformLogo Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWESonar.UWESonarFriendsSubsystem.HasCrossPlatformPrivileges
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUWESonarFriendsSubsystem::HasCrossPlatformPrivileges()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarFriendsSubsystem", "HasCrossPlatformPrivileges");

	Params::UWESonarFriendsSubsystem_HasCrossPlatformPrivileges Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWESonar.UWESonarFriendsSubsystem.NotifyOnExitGame
// (Final, Native, Public, BlueprintCallable)

void UUWESonarFriendsSubsystem::NotifyOnExitGame()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarFriendsSubsystem", "NotifyOnExitGame");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarFriendsSubsystem.OnInviteScreenAccept
// (Final, Native, Public, BlueprintCallable)

void UUWESonarFriendsSubsystem::OnInviteScreenAccept()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarFriendsSubsystem", "OnInviteScreenAccept");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarFriendsSubsystem.OnInviteScreenDecline
// (Final, Native, Public, BlueprintCallable)

void UUWESonarFriendsSubsystem::OnInviteScreenDecline()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarFriendsSubsystem", "OnInviteScreenDecline");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarFriendsSubsystem.OnWidgetPopped
// (Final, Native, Protected)
// Parameters:
// EUWEWindowManagerLayer                  LayerId                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    IsLast                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TSubclassOf<class UCommonActivatableWidget>WidgetClas                                             (Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWESonarFriendsSubsystem::OnWidgetPopped(EUWEWindowManagerLayer LayerId, bool IsLast, TSubclassOf<class UCommonActivatableWidget> WidgetClas)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarFriendsSubsystem", "OnWidgetPopped");

	Params::UWESonarFriendsSubsystem_OnWidgetPopped Parms{};

	Parms.LayerId = LayerId;
	Parms.IsLast = IsLast;
	Parms.WidgetClas = WidgetClas;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarFriendsSubsystem.RequestCrossPlatformFriends
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    FromUserInput                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWESonarFriendsSubsystem::RequestCrossPlatformFriends(bool FromUserInput)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarFriendsSubsystem", "RequestCrossPlatformFriends");

	Params::UWESonarFriendsSubsystem_RequestCrossPlatformFriends Parms{};

	Parms.FromUserInput = FromUserInput;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarFriendsSubsystem.GetPendingNewIncomingInviteCount
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UUWESonarFriendsSubsystem::GetPendingNewIncomingInviteCount() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarFriendsSubsystem", "GetPendingNewIncomingInviteCount");

	Params::UWESonarFriendsSubsystem_GetPendingNewIncomingInviteCount Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWESonar.UWESonarPlayerStateComponent.GetSonarPlayerId
// (Final, Native, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UUWESonarPlayerStateComponent::GetSonarPlayerId()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarPlayerStateComponent", "GetSonarPlayerId");

	Params::UWESonarPlayerStateComponent_GetSonarPlayerId Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWESonar.UWESonarPlayerStateComponent.SetSonarInfo
// (Final, Native, Public)
// Parameters:
// const class FString&                    _SonarPlayerId                                         (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    PlatformUserId                                         (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    _PlatformProvider                                      (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWESonarPlayerStateComponent::SetSonarInfo(const class FString& _SonarPlayerId, const class FString& PlatformUserId, const class FString& _PlatformProvider)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarPlayerStateComponent", "SetSonarInfo");

	Params::UWESonarPlayerStateComponent_SetSonarInfo Parms{};

	Parms._SonarPlayerId = std::move(_SonarPlayerId);
	Parms.PlatformUserId = std::move(PlatformUserId);
	Parms._PlatformProvider = std::move(_PlatformProvider);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarPlayerStateComponent.OnRep_SonarPlayerStateUpdated
// (Final, Native, Private, Const)

void UUWESonarPlayerStateComponent::OnRep_SonarPlayerStateUpdated() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarPlayerStateComponent", "OnRep_SonarPlayerStateUpdated");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarSubsystem.CheckTwitchAccountLink
// (Final, Native, Public, BlueprintCallable)

void UUWESonarSubsystem::CheckTwitchAccountLink()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "CheckTwitchAccountLink");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarSubsystem.CheckTwitchEntitlements
// (Final, Native, Public, BlueprintCallable)

void UUWESonarSubsystem::CheckTwitchEntitlements()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "CheckTwitchEntitlements");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarSubsystem.EndSonarSession
// (Final, Native, Public)
// Parameters:
// bool                                    bShouldRestart                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWESonarSubsystem::EndSonarSession(bool bShouldRestart)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "EndSonarSession");

	Params::UWESonarSubsystem_EndSonarSession Parms{};

	Parms.bShouldRestart = bShouldRestart;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarSubsystem.GetCurrentPlayMode
// (Final, Native, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// EUWEPlayMode                            ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

EUWEPlayMode UUWESonarSubsystem::GetCurrentPlayMode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "GetCurrentPlayMode");

	Params::UWESonarSubsystem_GetCurrentPlayMode Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWESonar.UWESonarSubsystem.GetCurrentPlayModeString
// (Final, Native, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UUWESonarSubsystem::GetCurrentPlayModeString()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "GetCurrentPlayModeString");

	Params::UWESonarSubsystem_GetCurrentPlayModeString Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWESonar.UWESonarSubsystem.HandleEffectiveUserPrivilegeChanged
// (Final, Native, Public)
// Parameters:
// const class UCommonUserInfo*            UserInfo                                               (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EUWEUserPrivilege                       Privilege                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bHasPrivilege                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWESonarSubsystem::HandleEffectiveUserPrivilegeChanged(const class UCommonUserInfo* UserInfo, EUWEUserPrivilege Privilege, bool bHasPrivilege)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "HandleEffectiveUserPrivilegeChanged");

	Params::UWESonarSubsystem_HandleEffectiveUserPrivilegeChanged Parms{};

	Parms.UserInfo = UserInfo;
	Parms.Privilege = Privilege;
	Parms.bHasPrivilege = bHasPrivilege;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarSubsystem.HandlerUserInitialized
// (Final, Native, Public)
// Parameters:
// const class UCommonUserInfo*            UserInfo                                               (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bSuccess                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FText&                      Error                                                  (Parm, NativeAccessSpecifierPublic)
// ECommonUserPrivilege                    RequestedPrivilege                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ECommonUserOnlineContext                OnlineContext                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWESonarSubsystem::HandlerUserInitialized(const class UCommonUserInfo* UserInfo, bool bSuccess, const class FText& Error, ECommonUserPrivilege RequestedPrivilege, ECommonUserOnlineContext OnlineContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "HandlerUserInitialized");

	Params::UWESonarSubsystem_HandlerUserInitialized Parms{};

	Parms.UserInfo = UserInfo;
	Parms.bSuccess = bSuccess;
	Parms.Error = std::move(Error);
	Parms.RequestedPrivilege = RequestedPrivilege;
	Parms.OnlineContext = OnlineContext;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarSubsystem.HandlerUserPrivileges
// (Final, Native, Public)
// Parameters:
// const class UCommonUserInfo*            UserInfo                                               (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ECommonUserPrivilege                    Privilege                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ECommonUserAvailability                 OldAvailability                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ECommonUserAvailability                 NewAvailability                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWESonarSubsystem::HandlerUserPrivileges(const class UCommonUserInfo* UserInfo, ECommonUserPrivilege Privilege, ECommonUserAvailability OldAvailability, ECommonUserAvailability NewAvailability)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "HandlerUserPrivileges");

	Params::UWESonarSubsystem_HandlerUserPrivileges Parms{};

	Parms.UserInfo = UserInfo;
	Parms.Privilege = Privilege;
	Parms.OldAvailability = OldAvailability;
	Parms.NewAvailability = NewAvailability;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarSubsystem.IsEnabled
// (Final, Native, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUWESonarSubsystem::IsEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "IsEnabled");

	Params::UWESonarSubsystem_IsEnabled Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWESonar.UWESonarSubsystem.RedeemEntitlementCode
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    ClaimCode                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWESonarSubsystem::RedeemEntitlementCode(const class FString& ClaimCode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "RedeemEntitlementCode");

	Params::UWESonarSubsystem_RedeemEntitlementCode Parms{};

	Parms.ClaimCode = std::move(ClaimCode);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarSubsystem.RequestTwitchLink
// (Final, Native, Public, BlueprintCallable)

void UUWESonarSubsystem::RequestTwitchLink()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "RequestTwitchLink");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarSubsystem.StartSonarSession
// (Final, Native, Public)

void UUWESonarSubsystem::StartSonarSession()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "StartSonarSession");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarSubsystem.UnLinkTwitchAccount
// (Final, Native, Public, BlueprintCallable)

void UUWESonarSubsystem::UnLinkTwitchAccount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "UnLinkTwitchAccount");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarSubsystem.UpdatePlayerEntitlements
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const TArray<class FString>&            EntitlementIds                                         (Parm, ZeroConstructor, NativeAccessSpecifierPublic)

void UUWESonarSubsystem::UpdatePlayerEntitlements(const TArray<class FString>& EntitlementIds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "UpdatePlayerEntitlements");

	Params::UWESonarSubsystem_UpdatePlayerEntitlements Parms{};

	Parms.EntitlementIds = std::move(EntitlementIds);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWESonarSubsystem.UpdateStatus
// (Final, Native, Public)

void UUWESonarSubsystem::UpdateStatus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESonarSubsystem", "UpdateStatus");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWEUserSubsystem.GetUserPrivilegeResult
// (Final, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure)
// Parameters:
// const struct FPlatformUserId&           PlatformUserId                                         (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EUWEUserPrivilege                       Privilege                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bShowResolveUIOnFailure                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ECommonUserPrivilegeResult              ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

ECommonUserPrivilegeResult UUWEUserSubsystem::GetUserPrivilegeResult(const struct FPlatformUserId& PlatformUserId, EUWEUserPrivilege Privilege, bool bShowResolveUIOnFailure)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEUserSubsystem", "GetUserPrivilegeResult");

	Params::UWEUserSubsystem_GetUserPrivilegeResult Parms{};

	Parms.PlatformUserId = std::move(PlatformUserId);
	Parms.Privilege = Privilege;
	Parms.bShowResolveUIOnFailure = bShowResolveUIOnFailure;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWESonar.UWEUserSubsystem.HandleUserPrivilegeChanged
// (Final, Native, Private)
// Parameters:
// const class UCommonUserInfo*            UserInfo                                               (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ECommonUserPrivilege                    Privilege                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ECommonUserAvailability                 OldAvailability                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ECommonUserAvailability                 NewAvailability                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEUserSubsystem::HandleUserPrivilegeChanged(const class UCommonUserInfo* UserInfo, ECommonUserPrivilege Privilege, ECommonUserAvailability OldAvailability, ECommonUserAvailability NewAvailability)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEUserSubsystem", "HandleUserPrivilegeChanged");

	Params::UWEUserSubsystem_HandleUserPrivilegeChanged Parms{};

	Parms.UserInfo = UserInfo;
	Parms.Privilege = Privilege;
	Parms.OldAvailability = OldAvailability;
	Parms.NewAvailability = NewAvailability;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWESonar.UWEUserSubsystem.CanSwitchPlatformUser
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUWEUserSubsystem::CanSwitchPlatformUser() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEUserSubsystem", "CanSwitchPlatformUser");

	Params::UWEUserSubsystem_CanSwitchPlatformUser Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWESonar.UWEUserSubsystem.GetFirstLoggedInUserInfo
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class UCommonUserInfo*                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UCommonUserInfo* UUWEUserSubsystem::GetFirstLoggedInUserInfo() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEUserSubsystem", "GetFirstLoggedInUserInfo");

	Params::UWEUserSubsystem_GetFirstLoggedInUserInfo Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWESonar.UWEUserSubsystem.HasLoggedInLocalUser
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUWEUserSubsystem::HasLoggedInLocalUser() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEUserSubsystem", "HasLoggedInLocalUser");

	Params::UWEUserSubsystem_HasLoggedInLocalUser Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

