#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWEWorldPopulation2

#include "Basic.hpp"

#include "UWEWorldPopulation2_classes.hpp"
#include "UWEWorldPopulation2_parameters.hpp"


namespace SDK
{

// Function UWEWorldPopulation2.UUWEWorldPop2BlueprintFunctionLibrary.GetAllResourcesInCylinderOfLocationFiltered
// (Final, BlueprintAuthorityOnly, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FVector&                   Location                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   HorizontalRadius                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   VerticalHalfHeight                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FUWEWorldPop2Query&        InFilter                                               (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// TArray<struct FUWESeededResourceInfo>*  OutResources                                           (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)

void UUUWEWorldPop2BlueprintFunctionLibrary::GetAllResourcesInCylinderOfLocationFiltered(class UObject* WorldContextObject, const struct FVector& Location, float HorizontalRadius, float VerticalHalfHeight, const struct FUWEWorldPop2Query& InFilter, TArray<struct FUWESeededResourceInfo>* OutResources)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UUWEWorldPop2BlueprintFunctionLibrary", "GetAllResourcesInCylinderOfLocationFiltered");

	Params::UUWEWorldPop2BlueprintFunctionLibrary_GetAllResourcesInCylinderOfLocationFiltered Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.Location = std::move(Location);
	Parms.HorizontalRadius = HorizontalRadius;
	Parms.VerticalHalfHeight = VerticalHalfHeight;
	Parms.InFilter = std::move(InFilter);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutResources != nullptr)
		*OutResources = std::move(Parms.OutResources);
}


// Function UWEWorldPopulation2.UUWEWorldPop2BlueprintFunctionLibrary.GetAllResourcesInRangeOfLocationFiltered
// (Final, BlueprintAuthorityOnly, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FVector&                   Location                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   Radius                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FUWEWorldPop2Query&        InFilter                                               (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// TArray<struct FUWESeededResourceInfo>*  OutResources                                           (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)

void UUUWEWorldPop2BlueprintFunctionLibrary::GetAllResourcesInRangeOfLocationFiltered(class UObject* WorldContextObject, const struct FVector& Location, float Radius, const struct FUWEWorldPop2Query& InFilter, TArray<struct FUWESeededResourceInfo>* OutResources)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UUWEWorldPop2BlueprintFunctionLibrary", "GetAllResourcesInRangeOfLocationFiltered");

	Params::UUWEWorldPop2BlueprintFunctionLibrary_GetAllResourcesInRangeOfLocationFiltered Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.Location = std::move(Location);
	Parms.Radius = Radius;
	Parms.InFilter = std::move(InFilter);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutResources != nullptr)
		*OutResources = std::move(Parms.OutResources);
}


// Function UWEWorldPopulation2.UUWEWorldPop2BlueprintFunctionLibrary.GetNumResourcesInRangeOfLocationFiltered
// (Final, BlueprintAuthorityOnly, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FVector&                   Location                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   Radius                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FUWEWorldPop2Query&        InFilter                                               (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UUUWEWorldPop2BlueprintFunctionLibrary::GetNumResourcesInRangeOfLocationFiltered(class UObject* WorldContextObject, const struct FVector& Location, float Radius, const struct FUWEWorldPop2Query& InFilter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UUWEWorldPop2BlueprintFunctionLibrary", "GetNumResourcesInRangeOfLocationFiltered");

	Params::UUWEWorldPop2BlueprintFunctionLibrary_GetNumResourcesInRangeOfLocationFiltered Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.Location = std::move(Location);
	Parms.Radius = Radius;
	Parms.InFilter = std::move(InFilter);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEWorldPopulation2.UUWEWorldPop2BlueprintFunctionLibrary.HasAnyResourcesInCylinderOfLocationFiltered
// (Final, BlueprintAuthorityOnly, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FVector&                   Location                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   HorizontalRadius                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   VerticalHalfHeight                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FUWEWorldPop2Query&        InFilter                                               (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UUUWEWorldPop2BlueprintFunctionLibrary::HasAnyResourcesInCylinderOfLocationFiltered(class UObject* WorldContextObject, const struct FVector& Location, float HorizontalRadius, float VerticalHalfHeight, const struct FUWEWorldPop2Query& InFilter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("UUWEWorldPop2BlueprintFunctionLibrary", "HasAnyResourcesInCylinderOfLocationFiltered");

	Params::UUWEWorldPop2BlueprintFunctionLibrary_HasAnyResourcesInCylinderOfLocationFiltered Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.Location = std::move(Location);
	Parms.HorizontalRadius = HorizontalRadius;
	Parms.VerticalHalfHeight = VerticalHalfHeight;
	Parms.InFilter = std::move(InFilter);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEWorldPopulation2.UWERegionLootDataAsset.GetLootEntriesForRegion
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const struct FGameplayTag&              RegionTag                                              (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FUWELootEntryList                ReturnValue                                            (Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)

struct FUWELootEntryList UUWERegionLootDataAsset::GetLootEntriesForRegion(const struct FGameplayTag& RegionTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWERegionLootDataAsset", "GetLootEntriesForRegion");

	Params::UWERegionLootDataAsset_GetLootEntriesForRegion Parms{};

	Parms.RegionTag = std::move(RegionTag);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEWorldPopulation2.UWERegionLootDataAsset.PickWeightedLootForRegion
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const struct FGameplayTag&              RegionTag                                              (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TSoftClassPtr<class UClass>             ReturnValue                                            (Parm, OutParm, ReturnParm, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

TSoftClassPtr<class UClass> UUWERegionLootDataAsset::PickWeightedLootForRegion(const struct FGameplayTag& RegionTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWERegionLootDataAsset", "PickWeightedLootForRegion");

	Params::UWERegionLootDataAsset_PickWeightedLootForRegion Parms{};

	Parms.RegionTag = std::move(RegionTag);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEWorldPopulation2.UWESpawnDataSubsystem.DebugForceLoadSpatialData
// (Final, Native, Public, BlueprintCallable)

void UUWESpawnDataSubsystem::DebugForceLoadSpatialData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESpawnDataSubsystem", "DebugForceLoadSpatialData");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWEWorldPopulation2.UWESpawnDataSubsystem.GetLocationDebugInfo
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FVector&                   Location                                               (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FUWEWorldPopLocationDebugInfo    ReturnValue                                            (Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)

struct FUWEWorldPopLocationDebugInfo UUWESpawnDataSubsystem::GetLocationDebugInfo(const struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESpawnDataSubsystem", "GetLocationDebugInfo");

	Params::UWESpawnDataSubsystem_GetLocationDebugInfo Parms{};

	Parms.Location = std::move(Location);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEWorldPopulation2.UWESpawnDataSubsystem.GetStringFromDebugLocationInfo
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FUWEWorldPopLocationDebugInfo&InInfo                                                 (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UUWESpawnDataSubsystem::GetStringFromDebugLocationInfo(const struct FUWEWorldPopLocationDebugInfo& InInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWESpawnDataSubsystem", "GetStringFromDebugLocationInfo");

	Params::UWESpawnDataSubsystem_GetStringFromDebugLocationInfo Parms{};

	Parms.InInfo = std::move(InInfo);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEWorldPopulation2.UWEWorldPopCreaturesSubsystem.ManagedCreatureDestroyed
// (Final, Native, Private)
// Parameters:
// class AActor*                           DestroyedActor                                         (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEWorldPopCreaturesSubsystem::ManagedCreatureDestroyed(class AActor* DestroyedActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEWorldPopCreaturesSubsystem", "ManagedCreatureDestroyed");

	Params::UWEWorldPopCreaturesSubsystem_ManagedCreatureDestroyed Parms{};

	Parms.DestroyedActor = DestroyedActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEWorldPopulation2.UWEWorldPopCreaturesSubsystem.RegisterExistingCreature
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// class AActor*                           creature                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FGuid&                     SpawnId                                                (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bIsPersistent                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FGameplayTagContainer&     RespawnAllowEncroachingTags                            (Parm, NativeAccessSpecifierPublic)
// const struct FUWEWorldPopCreatureData&  CreatureData                                           (Parm, NativeAccessSpecifierPublic)

void UUWEWorldPopCreaturesSubsystem::RegisterExistingCreature(class AActor* creature, const struct FGuid& SpawnId, bool bIsPersistent, const struct FGameplayTagContainer& RespawnAllowEncroachingTags, const struct FUWEWorldPopCreatureData& CreatureData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEWorldPopCreaturesSubsystem", "RegisterExistingCreature");

	Params::UWEWorldPopCreaturesSubsystem_RegisterExistingCreature Parms{};

	Parms.creature = creature;
	Parms.SpawnId = std::move(SpawnId);
	Parms.bIsPersistent = bIsPersistent;
	Parms.RespawnAllowEncroachingTags = std::move(RespawnAllowEncroachingTags);
	Parms.CreatureData = std::move(CreatureData);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEWorldPopulation2.UWEWorldPopCreaturesSubsystem.RequestSpawnManagedCreature
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FGuid&                     SpawnId                                                (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TSubclassOf<class AActor>               CreatureClass                                          (Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FTransform&                SpawnTransform                                         (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bPersistentLocation                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FUWEWorldPopCreatureData&  CreatureData                                           (Parm, NativeAccessSpecifierPublic)
// class AActor*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class AActor* UUWEWorldPopCreaturesSubsystem::RequestSpawnManagedCreature(const struct FGuid& SpawnId, TSubclassOf<class AActor> CreatureClass, const struct FTransform& SpawnTransform, bool bPersistentLocation, const struct FUWEWorldPopCreatureData& CreatureData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEWorldPopCreaturesSubsystem", "RequestSpawnManagedCreature");

	Params::UWEWorldPopCreaturesSubsystem_RequestSpawnManagedCreature Parms{};

	Parms.SpawnId = std::move(SpawnId);
	Parms.CreatureClass = CreatureClass;
	Parms.SpawnTransform = std::move(SpawnTransform);
	Parms.bPersistentLocation = bPersistentLocation;
	Parms.CreatureData = std::move(CreatureData);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEWorldPopulation2.UWEWorldPopCreaturesSubsystem.UnregisterExistingCreature
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FGuid&                     SpawnId                                                (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEWorldPopCreaturesSubsystem::UnregisterExistingCreature(const struct FGuid& SpawnId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEWorldPopCreaturesSubsystem", "UnregisterExistingCreature");

	Params::UWEWorldPopCreaturesSubsystem_UnregisterExistingCreature Parms{};

	Parms.SpawnId = std::move(SpawnId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEWorldPopulation2.UWEWorldPopCreaturesSubsystem.GetCreatureSpawnIDForActor
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class AActor*                           creature                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FGuid                            ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FGuid UUWEWorldPopCreaturesSubsystem::GetCreatureSpawnIDForActor(class AActor* creature) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEWorldPopCreaturesSubsystem", "GetCreatureSpawnIDForActor");

	Params::UWEWorldPopCreaturesSubsystem_GetCreatureSpawnIDForActor Parms{};

	Parms.creature = creature;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEWorldPopulation2.UWEWorldPopCreaturesSubsystem.GetCreatureSpawnsInRange
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const class UWorld*                     InWorldContext                                         (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FVector&                   FromLocation                                           (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   Range                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TSoftClassPtr<class UClass>             CreatureFilter                                         (Parm, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<struct FVector>*                 OutSpawnLocations                                      (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)

void UUWEWorldPopCreaturesSubsystem::GetCreatureSpawnsInRange(const class UWorld* InWorldContext, const struct FVector& FromLocation, float Range, TSoftClassPtr<class UClass> CreatureFilter, TArray<struct FVector>* OutSpawnLocations) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEWorldPopCreaturesSubsystem", "GetCreatureSpawnsInRange");

	Params::UWEWorldPopCreaturesSubsystem_GetCreatureSpawnsInRange Parms{};

	Parms.InWorldContext = InWorldContext;
	Parms.FromLocation = std::move(FromLocation);
	Parms.Range = Range;
	Parms.CreatureFilter = CreatureFilter;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutSpawnLocations != nullptr)
		*OutSpawnLocations = std::move(Parms.OutSpawnLocations);
}


// Function UWEWorldPopulation2.UWEWorldPopCreaturesSubsystem.GetCreatureSpawnStatus
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FGuid&                     SpawnId                                                (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ECreatureSpawnStatus                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

ECreatureSpawnStatus UUWEWorldPopCreaturesSubsystem::GetCreatureSpawnStatus(const struct FGuid& SpawnId) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEWorldPopCreaturesSubsystem", "GetCreatureSpawnStatus");

	Params::UWEWorldPopCreaturesSubsystem_GetCreatureSpawnStatus Parms{};

	Parms.SpawnId = std::move(SpawnId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function UWEWorldPopulation2.UWEWorldPopResourceBaseActor.OnHasBeenGathered
// (Event, Protected, BlueprintEvent)

void AUWEWorldPopResourceBaseActor::OnHasBeenGathered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEWorldPopResourceBaseActor", "OnHasBeenGathered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UWEWorldPopulation2.UWEWorldPopResourceBaseActor.OnRep_HasBeenGathered
// (Final, Native, Protected)

void AUWEWorldPopResourceBaseActor::OnRep_HasBeenGathered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEWorldPopResourceBaseActor", "OnRep_HasBeenGathered");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function UWEWorldPopulation2.UWEWorldPopSubsystem.DisableSpawnForClass
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TSoftClassPtr<class UClass>             Class_0                                                (Parm, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEWorldPopSubsystem::DisableSpawnForClass(TSoftClassPtr<class UClass> Class_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEWorldPopSubsystem", "DisableSpawnForClass");

	Params::UWEWorldPopSubsystem_DisableSpawnForClass Parms{};

	Parms.Class_0 = Class_0;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEWorldPopulation2.UWEWorldPopSubsystem.OnSpawnedResourceDestroyed
// (Final, Native, Private)
// Parameters:
// class AActor*                           SpawnedResource                                        (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUWEWorldPopSubsystem::OnSpawnedResourceDestroyed(class AActor* SpawnedResource)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEWorldPopSubsystem", "OnSpawnedResourceDestroyed");

	Params::UWEWorldPopSubsystem_OnSpawnedResourceDestroyed Parms{};

	Parms.SpawnedResource = SpawnedResource;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function UWEWorldPopulation2.UWEWorldZoneTrackerSubsystem.FindWorldZoneTag
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FVector&                   Location                                               (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FGameplayTag                     ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FGameplayTag UUWEWorldZoneTrackerSubsystem::FindWorldZoneTag(const struct FVector& Location) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEWorldZoneTrackerSubsystem", "FindWorldZoneTag");

	Params::UWEWorldZoneTrackerSubsystem_FindWorldZoneTag Parms{};

	Parms.Location = std::move(Location);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

