#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DatabankCategory

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_DatabankCategory.WBP_DatabankCategory_C
// 0x0060 (0x0508 - 0x04A8)
class UWBP_DatabankCategory_C final : public UCommonActivatableWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_UnreadBadge_C*                     UnreadBadge;                                       // 0x04B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               ToggleAndBadge;                                    // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_DatabankCategoryToggle_C*          Toggle;                                            // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           SubCategories;                                     // 0x04C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Glow;                                              // 0x04D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           Entries;                                           // 0x04D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USN2DatabankCategoryViewModel*          ViewModel;                                         // 0x04E0(0x0008)(BlueprintVisible, ZeroConstructor, Transient, DuplicateTransient, RepSkip, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class USN2DatabankEntryViewModel* Entry)> OnEntryClicked;          // 0x04E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          HideToggle;                                        // 0x04F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4F9[0x7];                                      // 0x04F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_DatabankEntryDetail_C*             DatabankEntryDetail;                               // 0x0500(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void BndEvt__WBP_DatabankCategory_Toggle_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BP_OnActivated();
	void BP_OnDeactivated();
	void Construct();
	void ExecuteUbergraph_WBP_DatabankCategory(int32 EntryPoint);
	void Find_Entry(class UUWEDatabankEntry* DatabankEntry, class UWBP_DatabankEntryWrapper_C** Widget);
	void Forward_Entry_Clicked(class USN2DatabankEntryViewModel* Entry);
	void GetLastEntry(class UWidget** Widget);
	void OnEntryButtonClick(class UCommonButtonBase* Entry);
	void RefreshEntries(const TArray<class USN2DatabankEntryViewModel*>& New_Entries);
	void RefreshSubCategories(const TArray<class USN2DatabankCategoryViewModel*>& Categories);
	void SetExpanded(bool IsExpanded);
	void SetIndentLevel(int32 Indent_Level);
	void SetViewModel(class USN2DatabankCategoryViewModel* ViewModel_0);

	ESlateVisibility __873325e4_4154_03a8_b772_e89ae1be6e49_SourceToDest() const;
	ESlateVisibility __a8c71d49_429a_c9f0_ee5d_d5bc0c0cd251_SourceToDest() const;
	ESlateVisibility __ad9217fb_40b8_1f15_1ac6_9cb5b02bbf6b_SourceToDest() const;
	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_DatabankCategory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_DatabankCategory_C")
	}
	static class UWBP_DatabankCategory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DatabankCategory_C>();
	}
};
DUMPER7_ASSERTS_UWBP_DatabankCategory_C;

}

