#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IncompleteFeedbackDialog

#include "Basic.hpp"

#include "WBP_IncompleteFeedbackDialog_classes.hpp"
#include "WBP_IncompleteFeedbackDialog_parameters.hpp"


namespace SDK
{

// Function WBP_IncompleteFeedbackDialog.WBP_IncompleteFeedbackDialog_C.BndEvt__WBP_DirtySettingsDialog_OKButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_IncompleteFeedbackDialog_C::BndEvt__WBP_DirtySettingsDialog_OKButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IncompleteFeedbackDialog_C", "BndEvt__WBP_DirtySettingsDialog_OKButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_IncompleteFeedbackDialog_C_BndEvt__WBP_DirtySettingsDialog_OKButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IncompleteFeedbackDialog.WBP_IncompleteFeedbackDialog_C.ExecuteUbergraph_WBP_IncompleteFeedbackDialog
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IncompleteFeedbackDialog_C::ExecuteUbergraph_WBP_IncompleteFeedbackDialog(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IncompleteFeedbackDialog_C", "ExecuteUbergraph_WBP_IncompleteFeedbackDialog");

	Params::WBP_IncompleteFeedbackDialog_C_ExecuteUbergraph_WBP_IncompleteFeedbackDialog Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IncompleteFeedbackDialog.WBP_IncompleteFeedbackDialog_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IncompleteFeedbackDialog_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IncompleteFeedbackDialog_C", "PreConstruct");

	Params::WBP_IncompleteFeedbackDialog_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IncompleteFeedbackDialog.WBP_IncompleteFeedbackDialog_C.SetMessages
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    DisplayWhatHappened                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    DisplayHowDoYouFeel                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IncompleteFeedbackDialog_C::SetMessages(bool DisplayWhatHappened, bool DisplayHowDoYouFeel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IncompleteFeedbackDialog_C", "SetMessages");

	Params::WBP_IncompleteFeedbackDialog_C_SetMessages Parms{};

	Parms.DisplayWhatHappened = DisplayWhatHappened;
	Parms.DisplayHowDoYouFeel = DisplayHowDoYouFeel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IncompleteFeedbackDialog.WBP_IncompleteFeedbackDialog_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_IncompleteFeedbackDialog_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IncompleteFeedbackDialog_C", "BP_GetDesiredFocusTarget");

	Params::WBP_IncompleteFeedbackDialog_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

