#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Tadpole_Attribute_RadialBar

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Tadpole_Attribute_RadialBar.WBP_Tadpole_Attribute_RadialBar_C
// 0x0068 (0x03D0 - 0x0368)
class UWBP_Tadpole_Attribute_RadialBar_C final : public UCommonUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0368(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonTextBlock*                       TextBlock;                                         // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Icon;                                              // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       ValueChange;                                       // 0x0380(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class USN2GasAttributeViewModel*              SN2GasAttributeViewModel;                          // 0x0388(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, DisableEditOnInstance, DuplicateTransient, RepSkip, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              IconTexture;                                       // 0x0390(0x0028)(Edit, BlueprintVisible, UObjectWrapper, HasGetValueTypeHash)
	struct FSlateColor                            TintColor;                                         // 0x03B8(0x0014)(Edit, BlueprintVisible)
	bool                                          AnimateValueChange;                                // 0x03CC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Tadpole_Attribute_RadialBar(int32 EntryPoint);
	void HandleValueUpdate(double Value);
	void PreConstruct(bool IsDesignTime);

	void GetTextValue(double FloatValue, class FText* TextValue) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Tadpole_Attribute_RadialBar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Tadpole_Attribute_RadialBar_C")
	}
	static class UWBP_Tadpole_Attribute_RadialBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Tadpole_Attribute_RadialBar_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Tadpole_Attribute_RadialBar_C;

}

