#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PingColorSwatchBar

#include "Basic.hpp"

#include "WBP_PingColorSwatchBar_classes.hpp"
#include "WBP_PingColorSwatchBar_parameters.hpp"


namespace SDK
{

// Function WBP_PingColorSwatchBar.WBP_PingColorSwatchBar_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PingColorSwatchBar_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PingColorSwatchBar_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PingColorSwatchBar.WBP_PingColorSwatchBar_C.ExecuteUbergraph_WBP_PingColorSwatchBar
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PingColorSwatchBar_C::ExecuteUbergraph_WBP_PingColorSwatchBar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PingColorSwatchBar_C", "ExecuteUbergraph_WBP_PingColorSwatchBar");

	Params::WBP_PingColorSwatchBar_C_ExecuteUbergraph_WBP_PingColorSwatchBar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PingColorSwatchBar.WBP_PingColorSwatchBar_C.HandleSwatchSelected
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsChecked                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWBP_ColorSwatch_C*               Swatch                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_PingColorSwatchBar_C::HandleSwatchSelected(bool IsChecked, class UWBP_ColorSwatch_C* Swatch)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PingColorSwatchBar_C", "HandleSwatchSelected");

	Params::WBP_PingColorSwatchBar_C_HandleSwatchSelected Parms{};

	Parms.IsChecked = IsChecked;
	Parms.Swatch = Swatch;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PingColorSwatchBar.WBP_PingColorSwatchBar_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_PingColorSwatchBar_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PingColorSwatchBar_C", "OnAddedToFocusPath");

	Params::WBP_PingColorSwatchBar_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PingColorSwatchBar.WBP_PingColorSwatchBar_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_PingColorSwatchBar_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PingColorSwatchBar_C", "OnFocusReceived");

	Params::WBP_PingColorSwatchBar_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_PingColorSwatchBar.WBP_PingColorSwatchBar_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_PingColorSwatchBar_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PingColorSwatchBar_C", "OnRemovedFromFocusPath");

	Params::WBP_PingColorSwatchBar_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PingColorSwatchBar.WBP_PingColorSwatchBar_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PingColorSwatchBar_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PingColorSwatchBar_C", "PreConstruct");

	Params::WBP_PingColorSwatchBar_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PingColorSwatchBar.WBP_PingColorSwatchBar_C.SetSelectedColor
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLinearColor&              SelectedColor_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PingColorSwatchBar_C::SetSelectedColor(const struct FLinearColor& SelectedColor_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PingColorSwatchBar_C", "SetSelectedColor");

	Params::WBP_PingColorSwatchBar_C_SetSelectedColor Parms{};

	Parms.SelectedColor_0 = std::move(SelectedColor_0);

	UObject::ProcessEvent(Func, &Parms);
}

}

