#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_StartScreen_Gamma

#include "Basic.hpp"

#include "WBP_StartScreen_Gamma_classes.hpp"
#include "WBP_StartScreen_Gamma_parameters.hpp"


namespace SDK
{

// Function WBP_StartScreen_Gamma.WBP_StartScreen_Gamma_C.AdjustGamma
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EScrollDirection                        Direction                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_StartScreen_Gamma_C::AdjustGamma(EScrollDirection Direction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StartScreen_Gamma_C", "AdjustGamma");

	Params::WBP_StartScreen_Gamma_C_AdjustGamma Parms{};

	Parms.Direction = Direction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StartScreen_Gamma.WBP_StartScreen_Gamma_C.BndEvt__WBP_StartScreen_Gamma_ConfirmBtn_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_StartScreen_Gamma_C::BndEvt__WBP_StartScreen_Gamma_ConfirmBtn_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StartScreen_Gamma_C", "BndEvt__WBP_StartScreen_Gamma_ConfirmBtn_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_StartScreen_Gamma_C_BndEvt__WBP_StartScreen_Gamma_ConfirmBtn_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StartScreen_Gamma.WBP_StartScreen_Gamma_C.BndEvt__WBP_StartScreen_Gamma_ResetBtn_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_StartScreen_Gamma_C::BndEvt__WBP_StartScreen_Gamma_ResetBtn_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StartScreen_Gamma_C", "BndEvt__WBP_StartScreen_Gamma_ResetBtn_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_StartScreen_Gamma_C_BndEvt__WBP_StartScreen_Gamma_ResetBtn_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StartScreen_Gamma.WBP_StartScreen_Gamma_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWBP_StartScreen_Gamma_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StartScreen_Gamma_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StartScreen_Gamma.WBP_StartScreen_Gamma_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_StartScreen_Gamma_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StartScreen_Gamma_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StartScreen_Gamma.WBP_StartScreen_Gamma_C.ExecuteUbergraph_WBP_StartScreen_Gamma
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_StartScreen_Gamma_C::ExecuteUbergraph_WBP_StartScreen_Gamma(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StartScreen_Gamma_C", "ExecuteUbergraph_WBP_StartScreen_Gamma");

	Params::WBP_StartScreen_Gamma_C_ExecuteUbergraph_WBP_StartScreen_Gamma Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StartScreen_Gamma.WBP_StartScreen_Gamma_C.Finished_E4C344DD48EC751E6999D4BD9BDC28A4
// (BlueprintCallable, BlueprintEvent)

void UWBP_StartScreen_Gamma_C::Finished_E4C344DD48EC751E6999D4BD9BDC28A4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StartScreen_Gamma_C", "Finished_E4C344DD48EC751E6999D4BD9BDC28A4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StartScreen_Gamma.WBP_StartScreen_Gamma_C.NeedsToShow
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   NeedsToShow_0                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_StartScreen_Gamma_C::NeedsToShow(bool* NeedsToShow_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StartScreen_Gamma_C", "NeedsToShow");

	Params::WBP_StartScreen_Gamma_C_NeedsToShow Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NeedsToShow_0 != nullptr)
		*NeedsToShow_0 = Parms.NeedsToShow_0;
}


// Function WBP_StartScreen_Gamma.WBP_StartScreen_Gamma_C.OnKeyDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_StartScreen_Gamma_C::OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StartScreen_Gamma_C", "OnKeyDown");

	Params::WBP_StartScreen_Gamma_C_OnKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_StartScreen_Gamma.WBP_StartScreen_Gamma_C.OnValueChanged_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_StartScreen_Gamma_C::OnValueChanged_Event(double Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StartScreen_Gamma_C", "OnValueChanged_Event");

	Params::WBP_StartScreen_Gamma_C_OnValueChanged_Event Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}

}

