#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GameModeButton

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "FMODStudio_structs.hpp"


namespace SDK::Params
{

// Function WBP_GameModeButton.WBP_GameModeButton_C.ExecuteUbergraph_WBP_GameModeButton
// 0x0078 (0x0078 - 0x0000)
struct WBP_GameModeButton_C_ExecuteUbergraph_WBP_GameModeButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue_1;              // 0x0018(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue_2;              // 0x0028(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue_3;              // 0x0038(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue_4;              // 0x0048(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FFMODEventInstance                     CallFunc_PlayEvent2D_ReturnValue;                  // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue_5;              // 0x0060(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FFMODEventInstance                     CallFunc_PlayEvent2D_ReturnValue_1;                // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_GameModeButton_C_ExecuteUbergraph_WBP_GameModeButton;

// Function WBP_GameModeButton.WBP_GameModeButton_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_GameModeButton_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GameModeButton_C_PreConstruct;

}

