#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PowerTerminalReserveScreen

#include "Basic.hpp"

#include "WBP_PowerTerminalReserveScreen_classes.hpp"
#include "WBP_PowerTerminalReserveScreen_parameters.hpp"


namespace SDK
{

// Function WBP_PowerTerminalReserveScreen.WBP_PowerTerminalReserveScreen_C.ExecuteUbergraph_WBP_PowerTerminalReserveScreen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PowerTerminalReserveScreen_C::ExecuteUbergraph_WBP_PowerTerminalReserveScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PowerTerminalReserveScreen_C", "ExecuteUbergraph_WBP_PowerTerminalReserveScreen");

	Params::WBP_PowerTerminalReserveScreen_C_ExecuteUbergraph_WBP_PowerTerminalReserveScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PowerTerminalReserveScreen.WBP_PowerTerminalReserveScreen_C.SetEnabledText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enabled                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PowerTerminalReserveScreen_C::SetEnabledText(bool Enabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PowerTerminalReserveScreen_C", "SetEnabledText");

	Params::WBP_PowerTerminalReserveScreen_C_SetEnabledText Parms{};

	Parms.Enabled = Enabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PowerTerminalReserveScreen.WBP_PowerTerminalReserveScreen_C.SetHeaderText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_PowerTerminalReserveScreen_C::SetHeaderText(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PowerTerminalReserveScreen_C", "SetHeaderText");

	Params::WBP_PowerTerminalReserveScreen_C_SetHeaderText Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}

}

